import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Wrench } from "lucide-react";
import { useState } from "react";
import { Link, useSearchParams } from "react-router";
import { toast } from "sonner";
import { agentQueries } from "@/entities/agent";
import { apiConnectionQueries, type ApiConnection } from "@/entities/api-connection";
import { mcpServerQueries, McpStatusBadge, type McpServer } from "@/entities/mcp-server";
import { isStructuredParam, toolQueries, type HttpTool, type ToolParam } from "@/entities/tool";
import { createApiConnection, updateApiConnection } from "@/features/api-connection-upsert";
import { replaceAgentTools } from "@/features/agent-tools-bind";
import { refreshMcpServer } from "@/features/mcp-server-refresh";
import { createMcpServer, updateMcpServer } from "@/features/mcp-server-upsert";
import { testHttpTool } from "@/features/tool-test-run";
import { ToolTransferActions } from "@/features/tool-transfer";
import { apiClient, useAuthSession, type components } from "@/shared/api";
import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, Input, Label, Tabs, TabsContent, TabsList, TabsTrigger, Textarea } from "@/shared/ui";
import { headerRows, headersRecord, secretHeadersPatch, validateDistinctHeaderNames, type HeaderRow } from "@/shared/lib";
import { needsSideEffectConfirmation } from "../model/tool-test-safety";
import { ApiConnectionForm } from "./api-connection-form";
import { McpServerForm } from "./mcp-server-form";

export function ToolsPage() {
  const connections = useQuery(apiConnectionQueries.list()); const tools = useQuery(toolQueries.list()); const servers = useQuery(mcpServerQueries.list()); const agents = useQuery(agentQueries.list()); const client = useQueryClient(); const canEdit = useAuthSession().user?.role !== "member";
  const [connectionForm, setConnectionForm] = useState(false); const [editingConnection, setEditingConnection] = useState<ApiConnection | null>(null); const [connectionPublicHeaders, setConnectionPublicHeaders] = useState<HeaderRow[]>([]); const [connectionSecretHeaders, setConnectionSecretHeaders] = useState<HeaderRow[]>([]); const [replaceConnectionSecrets, setReplaceConnectionSecrets] = useState(false);
  const [testingTool, setTestingTool] = useState<HttpTool | null>(null); const [testArgs, setTestArgs] = useState<Record<string, unknown>>({}); const [testResult, setTestResult] = useState<components["schemas"]["ToolTestResult"] | null>(null); const [search, setSearch] = useSearchParams(); const createdTool = tools.data?.find((item) => item.id === search.get("created")) ?? null; const clearCreated = () => setSearch((current) => { const next = new URLSearchParams(current); next.delete("created"); return next; }, { replace: true }); const [targetAgentId, setTargetAgentId] = useState("");
  const [serverForm, setServerForm] = useState(false); const [editingServer, setEditingServer] = useState<McpServer | null>(null); const [allowedTools, setAllowedTools] = useState<string[] | null>(null); const [mcpSecrets, setMcpSecrets] = useState<HeaderRow[]>([]); const [replaceMcpSecrets, setReplaceMcpSecrets] = useState(false);
  const reload = () => Promise.all([client.invalidateQueries({ queryKey: ["api-connections"] }), client.invalidateQueries({ queryKey: ["tools"] }), client.invalidateQueries({ queryKey: ["mcp-servers"] })]);
  const saveConnection = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = new FormData(event.currentTarget); try { const publicHeaderValues = headersRecord(connectionPublicHeaders); const secretPatch = secretHeadersPatch(Boolean(editingConnection), replaceConnectionSecrets, connectionSecretHeaders); validateDistinctHeaderNames(publicHeaderValues, secretPatch.secret_headers); const body = { slug: String(values.get("slug")), display_name: String(values.get("display_name")), base_url: String(values.get("base_url")), public_headers: publicHeaderValues, ...secretPatch }; if (editingConnection) await updateApiConnection(editingConnection.id, body); else await createApiConnection(body); await reload(); setConnectionForm(false); setEditingConnection(null); toast.success(editingConnection ? "API connection updated" : "API connection created"); } catch (error) { toast.error("Unable to save API connection", { description: error instanceof Error ? error.message : "Review the connection and try again." }); } };
  const saveServer = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = new FormData(event.currentTarget); try { const secretPatch = secretHeadersPatch(Boolean(editingServer), replaceMcpSecrets, mcpSecrets); const body = { slug: String(values.get("slug")), display_name: String(values.get("display_name")), url: String(values.get("url")), allowed_tools: allowedTools, ...secretPatch }; if (editingServer) await updateMcpServer(editingServer.id, body); else await createMcpServer(body); await reload(); setServerForm(false); setEditingServer(null); toast.success("Tool server saved"); } catch (error) { toast.error("Unable to save tool server", { description: error instanceof Error ? error.message : "Check the address and try again." }); } };
  const runTest = async (tool: HttpTool) => { if (needsSideEffectConfirmation(tool.method) && !window.confirm(`Testing a ${tool.method} request may change data in the target system. Continue?`)) return; try { setTestResult(await testHttpTool(tool.id, testArgs)); } catch { toast.error("Unable to send test request", { action: { label: "Try again", onClick: () => void runTest(tool) } }); } };
  const attachTool = async () => { if (!createdTool || !targetAgentId) return; try { const { data, error } = await apiClient.GET("/v1/agents/{agentId}/tools", { params: { path: { agentId: targetAgentId } } }); if (!data) throw error; await replaceAgentTools(targetAgentId, { ...data, tool_ids: [...new Set([...data.tool_ids, createdTool.id])] }); clearCreated(); toast.success("Tool attached to assistant"); } catch { toast.error("Unable to attach tool", { action: { label: "Try again", onClick: () => void attachTool() } }); } };
  const removeTool = async (tool: HttpTool) => { if (!window.confirm(`Delete tool “${tool.display_name}”?`)) return; try { const { response, error } = await apiClient.DELETE("/v1/tools/{toolId}", { params: { path: { toolId: tool.id } } }); if (!response.ok) throw error; await reload(); } catch { toast.error("Unable to delete tool", { action: { label: "Try again", onClick: () => void removeTool(tool) } }); } };
  const removeConnection = async (connection: ApiConnection) => { if (!window.confirm(`Delete API connection “${connection.display_name}”?`)) return; try { const { response, error } = await apiClient.DELETE("/v1/api-connections/{apiConnectionId}", { params: { path: { apiConnectionId: connection.id } } }); if (!response.ok) throw error; await reload(); } catch { toast.error("Unable to delete API connection", { description: "Remove or move the tools using this connection, then try again.", action: { label: "Try again", onClick: () => void removeConnection(connection) } }); } };
  const removeServer = async (server: McpServer) => { if (!window.confirm(`Delete connection “${server.display_name}”?`)) return; try { const { response, error } = await apiClient.DELETE("/v1/mcp-servers/{serverId}", { params: { path: { serverId: server.id } } }); if (!response.ok) throw error; await reload(); } catch { toast.error("Unable to delete connection", { action: { label: "Try again", onClick: () => void removeServer(server) } }); } };
  return <main className="space-y-6">{!canEdit ? <p className="text-sm text-muted-foreground">Only administrators can edit tools. Contact an administrator for help.</p> : null}{connections.isError || tools.isError || servers.isError ? <RetryCard onRetry={() => { void connections.refetch(); void tools.refetch(); void servers.refetch(); }} /> : null}
    <Tabs defaultValue="http"><TabsList><TabsTrigger value="connections">API connections</TabsTrigger><TabsTrigger value="http">HTTP tools</TabsTrigger><TabsTrigger value="mcp">Tool servers</TabsTrigger></TabsList>
      <TabsContent value="connections" className="space-y-4">{canEdit ? <div className="flex justify-end"><Button onClick={() => { setEditingConnection(null); setConnectionPublicHeaders([]); setConnectionSecretHeaders([]); setReplaceConnectionSecrets(false); setConnectionForm(true); }}><Plus />Connect API</Button></div> : null}<Dialog open={connectionForm && canEdit} onOpenChange={(open) => { setConnectionForm(open); if (!open) setEditingConnection(null); }}><DialogContent className="max-h-[90vh] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle>{editingConnection ? "Edit API connection" : "Connect an API"}</DialogTitle><DialogDescription>Save the base address and credentials once, then reuse them across HTTP tools.</DialogDescription></DialogHeader>{connectionForm && canEdit ? <ApiConnectionForm key={editingConnection?.id ?? "new-connection"} editing={editingConnection} publicHeaders={connectionPublicHeaders} secretHeaders={connectionSecretHeaders} replaceSecrets={replaceConnectionSecrets} onPublicHeaders={setConnectionPublicHeaders} onSecretHeaders={setConnectionSecretHeaders} onReplaceSecrets={setReplaceConnectionSecrets} onSubmit={saveConnection} onCancel={() => { setConnectionForm(false); setEditingConnection(null); }} /> : null}</DialogContent></Dialog>
        <div className="grid gap-4 lg:grid-cols-2">{connections.data?.map((connection) => <Card key={connection.id}><CardHeader><CardTitle>{connection.display_name}</CardTitle><CardDescription>{connection.base_url}</CardDescription></CardHeader><CardContent className="space-y-3"><div className="space-y-1 break-words text-sm text-muted-foreground"><p><span className="font-medium text-foreground">Public headers:</span> {publicHeaderSummary(connection.public_headers)}</p><p><span className="font-medium text-foreground">Secret headers:</span> {connection.secret_header_names.join(", ") || "None"}</p></div>{canEdit ? <div className="flex gap-2"><Button variant="ghost" onClick={() => { setEditingConnection(connection); setConnectionPublicHeaders(headerRows(connection.public_headers)); setConnectionSecretHeaders(connection.secret_header_names.map((name) => ({ id: crypto.randomUUID(), name, value: "" }))); setReplaceConnectionSecrets(false); setConnectionForm(true); }}>Edit connection</Button><Button variant="destructive" onClick={() => void removeConnection(connection)}>Delete</Button></div> : null}</CardContent></Card>)}</div>{connections.isSuccess && !connections.data.length ? <Empty title="No API connections yet" /> : null}
      </TabsContent>
      <TabsContent value="http" className="space-y-4"><div className="flex flex-wrap justify-end gap-2"><ToolTransferActions canImport={canEdit} onImported={reload} />{canEdit ? <Button asChild><Link to="/tools/new"><Plus />Create tool</Link></Button> : null}</div>
        {createdTool ? <Card><CardHeader><CardTitle>Attach tool to an assistant</CardTitle><CardDescription>Choose which assistant can use {createdTool.display_name}.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2">{agents.isLoading ? <p>Loading assistants…</p> : agents.isError ? <p className="text-sm text-destructive">Unable to load assistants. <Button variant="link" onClick={() => void agents.refetch()}>Try again</Button></p> : (agents.data ?? []).length ? <><select aria-label="Choose assistant" className="h-9 rounded-md border bg-background px-3" value={targetAgentId} onChange={(event) => setTargetAgentId(event.target.value)}><option value="">Choose assistant</option>{(agents.data ?? []).map((agent) => <option value={agent.id} key={agent.id}>{agent.name}</option>)}</select><Button disabled={!targetAgentId} onClick={attachTool}>Attach to assistant</Button>{targetAgentId ? <Button asChild variant="link"><Link to={`/agents/${targetAgentId}`}>Open assistant</Link></Button> : null}</> : <p className="text-sm text-muted-foreground">No assistants are available for this tool.</p>}</CardContent></Card> : null}
        <div className="grid gap-4 lg:grid-cols-2">{tools.data?.map((tool) => { const system = systemName(tool, connections.data); return <Card key={tool.id}><CardHeader>{system ? <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{system}</p> : null}<CardTitle>{tool.display_name}</CardTitle>{tool.description ? <CardDescription>{tool.description}</CardDescription> : null}</CardHeader>{canEdit ? <CardContent className="flex gap-2"><Button variant="outline" onClick={() => { setTestingTool(tool); setTestArgs({}); setTestResult(null); }}>Test</Button><Button asChild variant="ghost"><Link to={`/tools/${tool.id}/edit`}>Edit</Link></Button><Button variant="destructive" onClick={() => void removeTool(tool)}>Delete</Button></CardContent> : null}</Card>; })}</div>
        {testingTool ? <ToolTestPanel tool={testingTool} args={testArgs} result={testResult} onArgs={setTestArgs} onRun={() => void runTest(testingTool)} onClose={() => setTestingTool(null)} /> : null}{tools.isSuccess && !tools.data.length ? <Empty title="No HTTP tools yet" /> : null}
      </TabsContent>
      <TabsContent value="mcp" className="space-y-4">{canEdit ? <div className="flex justify-end"><Button onClick={() => { setEditingServer(null); setAllowedTools(null); setMcpSecrets([]); setReplaceMcpSecrets(false); setServerForm((value) => !value); }}><Plus />Connect server</Button></div> : null}{serverForm && canEdit ? <McpServerForm key={editingServer?.id ?? "new-server"} editing={editingServer} allowedTools={allowedTools} secretHeaders={mcpSecrets} replaceSecrets={replaceMcpSecrets} onAllowedTools={setAllowedTools} onSecretHeaders={setMcpSecrets} onReplaceSecrets={setReplaceMcpSecrets} onSubmit={saveServer} /> : null}
        <div className="grid gap-4 lg:grid-cols-2">{servers.data?.map((server) => <Card key={server.id}><CardHeader><div className="flex justify-between"><CardTitle>{server.display_name}</CardTitle><McpStatusBadge status={server.status} /></div><CardDescription>{server.tools.length} tools found</CardDescription>{server.status === "failing" ? <p role="alert" className="text-sm text-destructive">Unable to sync: {safeMcpError(server)}</p> : null}</CardHeader>{canEdit ? <CardContent className="flex flex-wrap gap-2"><Button variant="outline" onClick={async () => { try { await refreshMcpServer(server.id); await reload(); } catch { toast.error("Unable to refresh", { action: { label: "Try again", onClick: () => void refreshMcpServer(server.id).then(reload).catch(() => undefined) } }); } }}>{server.status === "failing" ? "Try refreshing" : "Refresh tool list"}</Button><Button variant="ghost" onClick={() => { setEditingServer(server); setAllowedTools(server.allowed_tools); setMcpSecrets(server.secret_header_names.map((name) => ({ id: crypto.randomUUID(), name, value: "" }))); setReplaceMcpSecrets(false); setServerForm(true); }}>Edit connection</Button><Button variant="destructive" onClick={() => void removeServer(server)}>Delete</Button></CardContent> : null}</Card>)}</div>{servers.isSuccess && !servers.data.length ? <Empty title="No tool servers connected" /> : null}
      </TabsContent>
    </Tabs>
  </main>;
}

type ToolTestResult = components["schemas"]["ToolTestResult"];
function ToolTestPanel({ tool, args, result, onArgs, onRun, onClose }: { tool: HttpTool; args: Record<string, unknown>; result: ToolTestResult | null; onArgs: (args: Record<string, unknown>) => void; onRun: () => void; onClose: () => void }) {
  const [jsonErrors, setJsonErrors] = useState<Record<string, string>>({});
  const setArgument = (param: ToolParam, raw: string) => {
    if (!isStructuredParam(param.type)) { onArgs({ ...args, [param.name]: parseArgument(raw, param.type) }); return; }
    const next = { ...args };
    if (!raw.trim()) { delete next[param.name]; setJsonErrors(withoutKey(jsonErrors, param.name)); onArgs(next); return; }
    const parsed = parseStructuredArgument(raw, param.type);
    if ("error" in parsed) { setJsonErrors({ ...jsonErrors, [param.name]: parsed.error }); return; }
    next[param.name] = parsed.value;
    setJsonErrors(withoutKey(jsonErrors, param.name));
    onArgs(next);
  };
  const blocked = Object.keys(jsonErrors).length > 0;
  return <Card><CardHeader><CardTitle>Test {tool.display_name}</CardTitle><CardDescription>{needsSideEffectConfirmation(tool.method) ? `Warning: ${tool.method} may change data in the target system.` : "This request only reads data."}</CardDescription></CardHeader><CardContent className="space-y-3">{tool.params.map((param) => <Label className="grid gap-2" key={param.name}>{param.description || param.name}{isStructuredParam(param.type) ? <Textarea required={param.required} rows={3} placeholder={param.type === "array" ? '["first", "second"]' : '{"key": "value"}'} onChange={(event) => setArgument(param, event.target.value)} /> : <Input required={param.required} type={param.type === "number" || param.type === "integer" ? "number" : "text"} onChange={(event) => setArgument(param, event.target.value)} />}{jsonErrors[param.name] ? <span role="alert" className="text-sm text-destructive">{jsonErrors[param.name]}</span> : null}</Label>)}<div className="flex gap-2"><Button onClick={onRun} disabled={blocked}>Send test</Button><Button variant="ghost" onClick={onClose}>Close</Button></div>{blocked ? <p className="text-sm text-muted-foreground">Fix the highlighted inputs before sending.</p> : null}{result ? <div className="rounded-xl border p-3 text-sm"><p>HTTP status: {result.status_code ?? "Not available"}</p><p>Duration: {result.duration_ms} ms</p>{result.truncated ? <p className="text-warning">The response was truncated.</p> : null}{result.error ? <p className="text-destructive">Error: {result.error.message}</p> : null}<pre className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap">{result.body || "No response content."}</pre></div> : null}</CardContent></Card>;
}
function withoutKey(source: Record<string, string>, key: string) { const next = { ...source }; delete next[key]; return next; }
function parseStructuredArgument(raw: string, type: ToolParam["type"]): { value: unknown } | { error: string } {
  let value: unknown;
  try { value = JSON.parse(raw); } catch { return { error: type === "array" ? 'Enter a JSON list, for example ["first", "second"].' : 'Enter a JSON object, for example {"key": "value"}.' }; }
  if (type === "array" && !Array.isArray(value)) return { error: "This input expects a list." };
  if (type === "object" && (typeof value !== "object" || value === null || Array.isArray(value))) return { error: "This input expects a group of named values." };
  return { value };
}
function RetryCard({ onRetry }: { onRetry: () => void }) { return <Card><CardContent className="pt-6">Unable to load tools. <Button variant="link" onClick={onRetry}>Try again</Button></CardContent></Card>; }
function Empty({ title }: { title: string }) { return <Card><CardHeader><Wrench /><CardTitle>{title}</CardTitle><CardDescription>Add a connection so assistants can use it.</CardDescription></CardHeader></Card>; }
function parseArgument(value: string, type: ToolParam["type"]) { if (type === "boolean") return value === "true"; if (type === "number" || type === "integer") return Number(value); return value; }
function safeMcpError(server: McpServer) { return (server.last_error?.message.trim() || "The server did not provide an error message.").slice(0, 500); }
/** Name of the system a tool talks to: its API connection, or "Direct URL" for tools that call an absolute address. Hidden until connections load so a stale id never shows a wrong label. */
function systemName(tool: HttpTool, connections: ApiConnection[] | undefined) { if (!tool.connection_id) return "Direct URL"; return connections?.find((item) => item.id === tool.connection_id)?.display_name ?? null; }
function publicHeaderSummary(headers: Record<string, string>) { const entries = Object.entries(headers).sort(([left], [right]) => left.localeCompare(right)); return entries.map(([name, value]) => `${name}: ${value}`).join(", ") || "None"; }
