// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_connections.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countToolsByAPIConnection = `-- name: CountToolsByAPIConnection :one
SELECT count(*) FROM tools WHERE connection_id=$1
`

func (q *Queries) CountToolsByAPIConnection(ctx context.Context, connectionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countToolsByAPIConnection, connectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIConnection = `-- name: CreateAPIConnection :exec
INSERT INTO api_connections (id,slug,display_name,base_url,public_headers,secret_headers_ciphertext,secret_header_names,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type CreateAPIConnectionParams struct {
	ID                      pgtype.UUID        `json:"id"`
	Slug                    string             `json:"slug"`
	DisplayName             string             `json:"display_name"`
	BaseUrl                 string             `json:"base_url"`
	PublicHeaders           []byte             `json:"public_headers"`
	SecretHeadersCiphertext []byte             `json:"secret_headers_ciphertext"`
	SecretHeaderNames       []string           `json:"secret_header_names"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAPIConnection(ctx context.Context, arg CreateAPIConnectionParams) error {
	_, err := q.db.Exec(ctx, createAPIConnection,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.BaseUrl,
		arg.PublicHeaders,
		arg.SecretHeadersCiphertext,
		arg.SecretHeaderNames,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAPIConnection = `-- name: DeleteAPIConnection :execrows
DELETE FROM api_connections WHERE id=$1
`

func (q *Queries) DeleteAPIConnection(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIConnection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIConnection = `-- name: GetAPIConnection :one
SELECT id, slug, display_name, base_url, public_headers, secret_headers_ciphertext, secret_header_names, created_at, updated_at FROM api_connections WHERE id=$1
`

func (q *Queries) GetAPIConnection(ctx context.Context, id pgtype.UUID) (ApiConnection, error) {
	row := q.db.QueryRow(ctx, getAPIConnection, id)
	var i ApiConnection
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.BaseUrl,
		&i.PublicHeaders,
		&i.SecretHeadersCiphertext,
		&i.SecretHeaderNames,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIConnectionForUpdate = `-- name: GetAPIConnectionForUpdate :one
SELECT id, slug, display_name, base_url, public_headers, secret_headers_ciphertext, secret_header_names, created_at, updated_at FROM api_connections WHERE id=$1 FOR UPDATE
`

func (q *Queries) GetAPIConnectionForUpdate(ctx context.Context, id pgtype.UUID) (ApiConnection, error) {
	row := q.db.QueryRow(ctx, getAPIConnectionForUpdate, id)
	var i ApiConnection
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.BaseUrl,
		&i.PublicHeaders,
		&i.SecretHeadersCiphertext,
		&i.SecretHeaderNames,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIConnections = `-- name: ListAPIConnections :many
SELECT id, slug, display_name, base_url, public_headers, secret_headers_ciphertext, secret_header_names, created_at, updated_at FROM api_connections
WHERE ($2::timestamptz IS NULL OR (created_at,id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC,id DESC LIMIT $1
`

type ListAPIConnectionsParams struct {
	Limit      int32              `json:"limit"`
	BeforeTime pgtype.Timestamptz `json:"before_time"`
	BeforeID   pgtype.UUID        `json:"before_id"`
}

func (q *Queries) ListAPIConnections(ctx context.Context, arg ListAPIConnectionsParams) ([]ApiConnection, error) {
	rows, err := q.db.Query(ctx, listAPIConnections, arg.Limit, arg.BeforeTime, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiConnection{}
	for rows.Next() {
		var i ApiConnection
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.BaseUrl,
			&i.PublicHeaders,
			&i.SecretHeadersCiphertext,
			&i.SecretHeaderNames,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAPIConnections = `-- name: ListAllAPIConnections :many
SELECT id, slug, display_name, base_url, public_headers, secret_headers_ciphertext, secret_header_names, created_at, updated_at FROM api_connections ORDER BY slug
`

func (q *Queries) ListAllAPIConnections(ctx context.Context) ([]ApiConnection, error) {
	rows, err := q.db.Query(ctx, listAllAPIConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiConnection{}
	for rows.Next() {
		var i ApiConnection
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.BaseUrl,
			&i.PublicHeaders,
			&i.SecretHeadersCiphertext,
			&i.SecretHeaderNames,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIConnection = `-- name: UpdateAPIConnection :execrows
UPDATE api_connections
SET slug=$2,display_name=$3,base_url=$4,public_headers=$5,secret_headers_ciphertext=$6,secret_header_names=$7,updated_at=$8
WHERE id=$1
`

type UpdateAPIConnectionParams struct {
	ID                      pgtype.UUID        `json:"id"`
	Slug                    string             `json:"slug"`
	DisplayName             string             `json:"display_name"`
	BaseUrl                 string             `json:"base_url"`
	PublicHeaders           []byte             `json:"public_headers"`
	SecretHeadersCiphertext []byte             `json:"secret_headers_ciphertext"`
	SecretHeaderNames       []string           `json:"secret_header_names"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAPIConnection(ctx context.Context, arg UpdateAPIConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAPIConnection,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.BaseUrl,
		arg.PublicHeaders,
		arg.SecretHeadersCiphertext,
		arg.SecretHeaderNames,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
