// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: async.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueWebhookDeliveries = `-- name: ClaimDueWebhookDeliveries :many
UPDATE webhook_deliveries SET
  attempts=attempts+1,
  locked_until=now()+($1::bigint * interval '1 millisecond')
WHERE id IN (
  SELECT id FROM webhook_deliveries
  WHERE status='pending' AND next_attempt_at<=now() AND (locked_until IS NULL OR locked_until<now())
  ORDER BY next_attempt_at,id FOR UPDATE SKIP LOCKED LIMIT $2
)
RETURNING id, run_id, api_key_id, url, event, payload, status, attempts, next_attempt_at, locked_until, last_status_code, last_error, delivered_at, created_at
`

type ClaimDueWebhookDeliveriesParams struct {
	LeaseMilliseconds int64 `json:"lease_milliseconds"`
	DeliveryLimit     int32 `json:"delivery_limit"`
}

func (q *Queries) ClaimDueWebhookDeliveries(ctx context.Context, arg ClaimDueWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, claimDueWebhookDeliveries, arg.LeaseMilliseconds, arg.DeliveryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ApiKeyID,
			&i.Url,
			&i.Event,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LockedUntil,
			&i.LastStatusCode,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimRunJobs = `-- name: ClaimRunJobs :many
UPDATE run_jobs SET locked_by=$1,
  locked_until=now()+($2::bigint * interval '1 millisecond'),
  attempts=attempts+1
WHERE run_id IN (
  SELECT run_id FROM run_jobs
  WHERE available_at<=now() AND (locked_until IS NULL OR locked_until<now())
  ORDER BY available_at,run_id FOR UPDATE SKIP LOCKED LIMIT $3
)
RETURNING run_id, available_at, locked_by, locked_until, attempts, created_at
`

type ClaimRunJobsParams struct {
	WorkerID          pgtype.Text `json:"worker_id"`
	LeaseMilliseconds int64       `json:"lease_milliseconds"`
	JobLimit          int32       `json:"job_limit"`
}

func (q *Queries) ClaimRunJobs(ctx context.Context, arg ClaimRunJobsParams) ([]RunJob, error) {
	rows, err := q.db.Query(ctx, claimRunJobs, arg.WorkerID, arg.LeaseMilliseconds, arg.JobLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunJob{}
	for rows.Next() {
		var i RunJob
		if err := rows.Scan(
			&i.RunID,
			&i.AvailableAt,
			&i.LockedBy,
			&i.LockedUntil,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeRunJob = `-- name: CompleteRunJob :execrows
DELETE FROM run_jobs WHERE run_id=$1 AND locked_by=$2
`

type CompleteRunJobParams struct {
	RunID    pgtype.UUID `json:"run_id"`
	LockedBy pgtype.Text `json:"locked_by"`
}

func (q *Queries) CompleteRunJob(ctx context.Context, arg CompleteRunJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeRunJob, arg.RunID, arg.LockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredIdempotency = `-- name: DeleteExpiredIdempotency :exec
DELETE FROM idempotency_keys WHERE expires_at<=$1
`

func (q *Queries) DeleteExpiredIdempotency(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotency, expiresAt)
	return err
}

const deleteExpiredIdempotencyKey = `-- name: DeleteExpiredIdempotencyKey :exec
DELETE FROM idempotency_keys
WHERE principal_kind=$1 AND principal_id=$2 AND key=$3 AND expires_at<=$4
`

type DeleteExpiredIdempotencyKeyParams struct {
	PrincipalKind string             `json:"principal_kind"`
	PrincipalID   pgtype.UUID        `json:"principal_id"`
	Key           string             `json:"key"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) DeleteExpiredIdempotencyKey(ctx context.Context, arg DeleteExpiredIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKey,
		arg.PrincipalKind,
		arg.PrincipalID,
		arg.Key,
		arg.ExpiresAt,
	)
	return err
}

const enqueueRun = `-- name: EnqueueRun :exec
INSERT INTO run_jobs (run_id,available_at,created_at) VALUES ($1,$2,$3)
`

type EnqueueRunParams struct {
	RunID       pgtype.UUID        `json:"run_id"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) EnqueueRun(ctx context.Context, arg EnqueueRunParams) error {
	_, err := q.db.Exec(ctx, enqueueRun, arg.RunID, arg.AvailableAt, arg.CreatedAt)
	return err
}

const extendRunJob = `-- name: ExtendRunJob :execrows
UPDATE run_jobs SET locked_until=now()+($1::bigint * interval '1 millisecond')
WHERE run_id=$2 AND locked_by=$3 AND locked_until>now()
`

type ExtendRunJobParams struct {
	LeaseMilliseconds int64       `json:"lease_milliseconds"`
	RunID             pgtype.UUID `json:"run_id"`
	WorkerID          pgtype.Text `json:"worker_id"`
}

func (q *Queries) ExtendRunJob(ctx context.Context, arg ExtendRunJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendRunJob, arg.LeaseMilliseconds, arg.RunID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT principal_kind, principal_id, key, request_hash, run_id, response_status, created_at, expires_at FROM idempotency_keys WHERE principal_kind=$1 AND principal_id=$2 AND key=$3
`

type GetIdempotencyKeyParams struct {
	PrincipalKind string      `json:"principal_kind"`
	PrincipalID   pgtype.UUID `json:"principal_id"`
	Key           string      `json:"key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.PrincipalKind, arg.PrincipalID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.PrincipalKind,
		&i.PrincipalID,
		&i.Key,
		&i.RequestHash,
		&i.RunID,
		&i.ResponseStatus,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, run_id, api_key_id, url, event, payload, status, attempts, next_attempt_at, locked_until, last_status_code, last_error, delivered_at, created_at FROM webhook_deliveries WHERE id=$1
`

func (q *Queries) GetWebhookDelivery(ctx context.Context, id pgtype.UUID) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ApiKeyID,
		&i.Url,
		&i.Event,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.LastStatusCode,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO idempotency_keys (
  principal_kind,principal_id,key,request_hash,run_id,response_status,created_at,expires_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT DO NOTHING
RETURNING principal_kind, principal_id, key, request_hash, run_id, response_status, created_at, expires_at
`

type InsertIdempotencyKeyParams struct {
	PrincipalKind  string             `json:"principal_kind"`
	PrincipalID    pgtype.UUID        `json:"principal_id"`
	Key            string             `json:"key"`
	RequestHash    []byte             `json:"request_hash"`
	RunID          pgtype.UUID        `json:"run_id"`
	ResponseStatus int32              `json:"response_status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyKey,
		arg.PrincipalKind,
		arg.PrincipalID,
		arg.Key,
		arg.RequestHash,
		arg.RunID,
		arg.ResponseStatus,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.PrincipalKind,
		&i.PrincipalID,
		&i.Key,
		&i.RequestHash,
		&i.RunID,
		&i.ResponseStatus,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :exec
INSERT INTO webhook_deliveries (
  id,run_id,api_key_id,url,event,payload,status,attempts,next_attempt_at,locked_until,
  last_status_code,last_error,delivered_at,created_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
`

type InsertWebhookDeliveryParams struct {
	ID             pgtype.UUID        `json:"id"`
	RunID          pgtype.UUID        `json:"run_id"`
	ApiKeyID       pgtype.UUID        `json:"api_key_id"`
	Url            string             `json:"url"`
	Event          string             `json:"event"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	LastStatusCode pgtype.Int4        `json:"last_status_code"`
	LastError      pgtype.Text        `json:"last_error"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertWebhookDelivery,
		arg.ID,
		arg.RunID,
		arg.ApiKeyID,
		arg.Url,
		arg.Event,
		arg.Payload,
		arg.Status,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.LockedUntil,
		arg.LastStatusCode,
		arg.LastError,
		arg.DeliveredAt,
		arg.CreatedAt,
	)
	return err
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, run_id, api_key_id, url, event, payload, status, attempts, next_attempt_at, locked_until, last_status_code, last_error, delivered_at, created_at FROM webhook_deliveries
WHERE run_id=$1
  AND ($2::timestamptz IS NULL OR (created_at,id)<($2,$3::uuid))
ORDER BY created_at DESC,id DESC LIMIT $4
`

type ListWebhookDeliveriesParams struct {
	RunID         pgtype.UUID        `json:"run_id"`
	BeforeTime    pgtype.Timestamptz `json:"before_time"`
	BeforeID      pgtype.UUID        `json:"before_id"`
	DeliveryLimit int32              `json:"delivery_limit"`
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries,
		arg.RunID,
		arg.BeforeTime,
		arg.BeforeID,
		arg.DeliveryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ApiKeyID,
			&i.Url,
			&i.Event,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LockedUntil,
			&i.LastStatusCode,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDelivered = `-- name: MarkWebhookDelivered :one
UPDATE webhook_deliveries SET status='delivered',locked_until=NULL,next_attempt_at=NULL,
  last_status_code=$2,last_error=NULL,delivered_at=$3
WHERE id=$1 AND status='pending'
RETURNING id, run_id, api_key_id, url, event, payload, status, attempts, next_attempt_at, locked_until, last_status_code, last_error, delivered_at, created_at
`

type MarkWebhookDeliveredParams struct {
	ID             pgtype.UUID        `json:"id"`
	LastStatusCode pgtype.Int4        `json:"last_status_code"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) MarkWebhookDelivered(ctx context.Context, arg MarkWebhookDeliveredParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, markWebhookDelivered, arg.ID, arg.LastStatusCode, arg.DeliveredAt)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ApiKeyID,
		&i.Url,
		&i.Event,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.LastStatusCode,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const markWebhookFailed = `-- name: MarkWebhookFailed :one
UPDATE webhook_deliveries SET status='failed',locked_until=NULL,next_attempt_at=NULL,
  last_status_code=$2,last_error=$3
WHERE id=$1 AND status='pending'
RETURNING id, run_id, api_key_id, url, event, payload, status, attempts, next_attempt_at, locked_until, last_status_code, last_error, delivered_at, created_at
`

type MarkWebhookFailedParams struct {
	ID             pgtype.UUID `json:"id"`
	LastStatusCode pgtype.Int4 `json:"last_status_code"`
	LastError      pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkWebhookFailed(ctx context.Context, arg MarkWebhookFailedParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, markWebhookFailed, arg.ID, arg.LastStatusCode, arg.LastError)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ApiKeyID,
		&i.Url,
		&i.Event,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.LastStatusCode,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const markWebhookRetry = `-- name: MarkWebhookRetry :one
UPDATE webhook_deliveries SET locked_until=NULL,next_attempt_at=$4,last_status_code=$2,last_error=$3
WHERE id=$1 AND status='pending'
RETURNING id, run_id, api_key_id, url, event, payload, status, attempts, next_attempt_at, locked_until, last_status_code, last_error, delivered_at, created_at
`

type MarkWebhookRetryParams struct {
	ID             pgtype.UUID        `json:"id"`
	LastStatusCode pgtype.Int4        `json:"last_status_code"`
	LastError      pgtype.Text        `json:"last_error"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
}

func (q *Queries) MarkWebhookRetry(ctx context.Context, arg MarkWebhookRetryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, markWebhookRetry,
		arg.ID,
		arg.LastStatusCode,
		arg.LastError,
		arg.NextAttemptAt,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ApiKeyID,
		&i.Url,
		&i.Event,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.LastStatusCode,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const resetWebhookDelivery = `-- name: ResetWebhookDelivery :one
UPDATE webhook_deliveries SET status='pending',attempts=0,next_attempt_at=$2,locked_until=NULL,
  last_status_code=NULL,last_error=NULL,delivered_at=NULL
WHERE id=$1 AND status='failed'
RETURNING id, run_id, api_key_id, url, event, payload, status, attempts, next_attempt_at, locked_until, last_status_code, last_error, delivered_at, created_at
`

type ResetWebhookDeliveryParams struct {
	ID            pgtype.UUID        `json:"id"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
}

func (q *Queries) ResetWebhookDelivery(ctx context.Context, arg ResetWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, resetWebhookDelivery, arg.ID, arg.NextAttemptAt)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ApiKeyID,
		&i.Url,
		&i.Event,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.LastStatusCode,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}
