// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveAgent = `-- name: ArchiveAgent :execrows
UPDATE agents SET archived_at=$2,updated_at=$2 WHERE id=$1 AND archived_at IS NULL
`

type ArchiveAgentParams struct {
	ID         pgtype.UUID        `json:"id"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) ArchiveAgent(ctx context.Context, arg ArchiveAgentParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveAgent, arg.ID, arg.ArchivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAgent = `-- name: CreateAgent :exec
INSERT INTO agents (id,name,description,provider_id,model,system_prompt,temperature,max_output_tokens,context_window_tokens,max_iterations,timeout_seconds,created_by,archived_at,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
`

type CreateAgentParams struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	Description         string             `json:"description"`
	ProviderID          pgtype.UUID        `json:"provider_id"`
	Model               string             `json:"model"`
	SystemPrompt        string             `json:"system_prompt"`
	Temperature         pgtype.Float8      `json:"temperature"`
	MaxOutputTokens     pgtype.Int4        `json:"max_output_tokens"`
	ContextWindowTokens int32              `json:"context_window_tokens"`
	MaxIterations       int32              `json:"max_iterations"`
	TimeoutSeconds      int32              `json:"timeout_seconds"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	ArchivedAt          pgtype.Timestamptz `json:"archived_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) error {
	_, err := q.db.Exec(ctx, createAgent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ProviderID,
		arg.Model,
		arg.SystemPrompt,
		arg.Temperature,
		arg.MaxOutputTokens,
		arg.ContextWindowTokens,
		arg.MaxIterations,
		arg.TimeoutSeconds,
		arg.CreatedBy,
		arg.ArchivedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createProvider = `-- name: CreateProvider :exec
INSERT INTO llm_providers (id,name,kind,base_url,api_key_ciphertext,api_key_hint,default_model,status,last_error,last_checked_at,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
`

type CreateProviderParams struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Kind             string             `json:"kind"`
	BaseUrl          pgtype.Text        `json:"base_url"`
	ApiKeyCiphertext []byte             `json:"api_key_ciphertext"`
	ApiKeyHint       pgtype.Text        `json:"api_key_hint"`
	DefaultModel     pgtype.Text        `json:"default_model"`
	Status           string             `json:"status"`
	LastError        []byte             `json:"last_error"`
	LastCheckedAt    pgtype.Timestamptz `json:"last_checked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) error {
	_, err := q.db.Exec(ctx, createProvider,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.BaseUrl,
		arg.ApiKeyCiphertext,
		arg.ApiKeyHint,
		arg.DefaultModel,
		arg.Status,
		arg.LastError,
		arg.LastCheckedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProvider = `-- name: DeleteProvider :execrows
DELETE FROM llm_providers WHERE id=$1
`

func (q *Queries) DeleteProvider(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProvider, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, description, provider_id, model, system_prompt, temperature, max_output_tokens, max_iterations, timeout_seconds, created_by, archived_at, created_at, updated_at, context_window_tokens FROM agents WHERE id=$1 AND archived_at IS NULL
`

func (q *Queries) GetAgent(ctx context.Context, id pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProviderID,
		&i.Model,
		&i.SystemPrompt,
		&i.Temperature,
		&i.MaxOutputTokens,
		&i.MaxIterations,
		&i.TimeoutSeconds,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContextWindowTokens,
	)
	return i, err
}

const getAgentForUpdate = `-- name: GetAgentForUpdate :one
SELECT id, name, description, provider_id, model, system_prompt, temperature, max_output_tokens, max_iterations, timeout_seconds, created_by, archived_at, created_at, updated_at, context_window_tokens FROM agents WHERE id=$1 AND archived_at IS NULL FOR UPDATE
`

func (q *Queries) GetAgentForUpdate(ctx context.Context, id pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentForUpdate, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProviderID,
		&i.Model,
		&i.SystemPrompt,
		&i.Temperature,
		&i.MaxOutputTokens,
		&i.MaxIterations,
		&i.TimeoutSeconds,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContextWindowTokens,
	)
	return i, err
}

const getProvider = `-- name: GetProvider :one
SELECT id, name, kind, base_url, api_key_ciphertext, api_key_hint, default_model, status, last_error, last_checked_at, created_at, updated_at, revision FROM llm_providers WHERE id=$1
`

func (q *Queries) GetProvider(ctx context.Context, id pgtype.UUID) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.BaseUrl,
		&i.ApiKeyCiphertext,
		&i.ApiKeyHint,
		&i.DefaultModel,
		&i.Status,
		&i.LastError,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}

const getProviderForUpdate = `-- name: GetProviderForUpdate :one
SELECT id, name, kind, base_url, api_key_ciphertext, api_key_hint, default_model, status, last_error, last_checked_at, created_at, updated_at, revision FROM llm_providers WHERE id=$1 FOR UPDATE
`

func (q *Queries) GetProviderForUpdate(ctx context.Context, id pgtype.UUID) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, getProviderForUpdate, id)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.BaseUrl,
		&i.ApiKeyCiphertext,
		&i.ApiKeyHint,
		&i.DefaultModel,
		&i.Status,
		&i.LastError,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, description, provider_id, model, system_prompt, temperature, max_output_tokens, max_iterations, timeout_seconds, created_by, archived_at, created_at, updated_at, context_window_tokens FROM agents WHERE archived_at IS NULL AND ($2::timestamptz IS NULL OR (created_at,id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC,id DESC LIMIT $1
`

type ListAgentsParams struct {
	Limit      int32              `json:"limit"`
	BeforeTime pgtype.Timestamptz `json:"before_time"`
	BeforeID   pgtype.UUID        `json:"before_id"`
}

func (q *Queries) ListAgents(ctx context.Context, arg ListAgentsParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents, arg.Limit, arg.BeforeTime, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ProviderID,
			&i.Model,
			&i.SystemPrompt,
			&i.Temperature,
			&i.MaxOutputTokens,
			&i.MaxIterations,
			&i.TimeoutSeconds,
			&i.CreatedBy,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContextWindowTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByProvider = `-- name: ListAgentsByProvider :many
SELECT id,name FROM agents WHERE provider_id=$1 AND archived_at IS NULL ORDER BY name,id
`

type ListAgentsByProviderRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) ListAgentsByProvider(ctx context.Context, providerID pgtype.UUID) ([]ListAgentsByProviderRow, error) {
	rows, err := q.db.Query(ctx, listAgentsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsByProviderRow{}
	for rows.Next() {
		var i ListAgentsByProviderRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, kind, base_url, api_key_ciphertext, api_key_hint, default_model, status, last_error, last_checked_at, created_at, updated_at, revision FROM llm_providers WHERE ($2::timestamptz IS NULL OR (created_at,id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC,id DESC LIMIT $1
`

type ListProvidersParams struct {
	Limit      int32              `json:"limit"`
	BeforeTime pgtype.Timestamptz `json:"before_time"`
	BeforeID   pgtype.UUID        `json:"before_id"`
}

func (q *Queries) ListProviders(ctx context.Context, arg ListProvidersParams) ([]LlmProvider, error) {
	rows, err := q.db.Query(ctx, listProviders, arg.Limit, arg.BeforeTime, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmProvider{}
	for rows.Next() {
		var i LlmProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.BaseUrl,
			&i.ApiKeyCiphertext,
			&i.ApiKeyHint,
			&i.DefaultModel,
			&i.Status,
			&i.LastError,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCatalog = `-- name: LockCatalog :exec
SELECT pg_advisory_xact_lock(724391821)
`

func (q *Queries) LockCatalog(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockCatalog)
	return err
}

const recordProviderCheck = `-- name: RecordProviderCheck :execrows
UPDATE llm_providers SET status=$3,last_error=$4,last_checked_at=$5,updated_at=$5
WHERE id=$1 AND revision=$2
`

type RecordProviderCheckParams struct {
	ID            pgtype.UUID        `json:"id"`
	Revision      int64              `json:"revision"`
	Status        string             `json:"status"`
	LastError     []byte             `json:"last_error"`
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
}

func (q *Queries) RecordProviderCheck(ctx context.Context, arg RecordProviderCheckParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordProviderCheck,
		arg.ID,
		arg.Revision,
		arg.Status,
		arg.LastError,
		arg.LastCheckedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAgent = `-- name: UpdateAgent :execrows
UPDATE agents SET name=$2,description=$3,provider_id=$4,model=$5,system_prompt=$6,temperature=$7,max_output_tokens=$8,context_window_tokens=$9,max_iterations=$10,timeout_seconds=$11,updated_at=$12
WHERE id=$1 AND archived_at IS NULL
`

type UpdateAgentParams struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	Description         string             `json:"description"`
	ProviderID          pgtype.UUID        `json:"provider_id"`
	Model               string             `json:"model"`
	SystemPrompt        string             `json:"system_prompt"`
	Temperature         pgtype.Float8      `json:"temperature"`
	MaxOutputTokens     pgtype.Int4        `json:"max_output_tokens"`
	ContextWindowTokens int32              `json:"context_window_tokens"`
	MaxIterations       int32              `json:"max_iterations"`
	TimeoutSeconds      int32              `json:"timeout_seconds"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAgent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ProviderID,
		arg.Model,
		arg.SystemPrompt,
		arg.Temperature,
		arg.MaxOutputTokens,
		arg.ContextWindowTokens,
		arg.MaxIterations,
		arg.TimeoutSeconds,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE llm_providers SET name=$2,kind=$3,base_url=$4,api_key_ciphertext=$5,api_key_hint=$6,default_model=$7,status=$8,last_error=$9,last_checked_at=$10,updated_at=$11,revision=revision+1
WHERE id=$1 RETURNING id, name, kind, base_url, api_key_ciphertext, api_key_hint, default_model, status, last_error, last_checked_at, created_at, updated_at, revision
`

type UpdateProviderParams struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Kind             string             `json:"kind"`
	BaseUrl          pgtype.Text        `json:"base_url"`
	ApiKeyCiphertext []byte             `json:"api_key_ciphertext"`
	ApiKeyHint       pgtype.Text        `json:"api_key_hint"`
	DefaultModel     pgtype.Text        `json:"default_model"`
	Status           string             `json:"status"`
	LastError        []byte             `json:"last_error"`
	LastCheckedAt    pgtype.Timestamptz `json:"last_checked_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.BaseUrl,
		arg.ApiKeyCiphertext,
		arg.ApiKeyHint,
		arg.DefaultModel,
		arg.Status,
		arg.LastError,
		arg.LastCheckedAt,
		arg.UpdatedAt,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.BaseUrl,
		&i.ApiKeyCiphertext,
		&i.ApiKeyHint,
		&i.DefaultModel,
		&i.Status,
		&i.LastError,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}
