// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveOwners = `-- name: CountActiveOwners :one
SELECT count(*) FROM users WHERE role='owner' AND status='active'
`

func (q *Queries) CountActiveOwners(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOwners)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (id,name,prefix,key_hash,scopes,webhook_secret_ciphertext,created_by,last_used_at,revoked_at,created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type CreateAPIKeyParams struct {
	ID                      pgtype.UUID        `json:"id"`
	Name                    string             `json:"name"`
	Prefix                  string             `json:"prefix"`
	KeyHash                 []byte             `json:"key_hash"`
	Scopes                  []string           `json:"scopes"`
	WebhookSecretCiphertext []byte             `json:"webhook_secret_ciphertext"`
	CreatedBy               pgtype.UUID        `json:"created_by"`
	LastUsedAt              pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt               pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey,
		arg.ID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
		arg.Scopes,
		arg.WebhookSecretCiphertext,
		arg.CreatedBy,
		arg.LastUsedAt,
		arg.RevokedAt,
		arg.CreatedAt,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id,user_id,family_id,token_hash,expires_at,revoked_at,replaced_by,created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
`

type CreateRefreshTokenParams struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	FamilyID   pgtype.UUID        `json:"family_id"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.ReplacedBy,
		arg.CreatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, password_hash, name, role, status, must_change_password, last_login_at, created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type CreateUserParams struct {
	ID                 pgtype.UUID        `json:"id"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	Name               string             `json:"name"`
	Role               string             `json:"role"`
	Status             string             `json:"status"`
	MustChangePassword bool               `json:"must_change_password"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
		arg.Status,
		arg.MustChangePassword,
		arg.LastLoginAt,
		arg.CreatedAt,
	)
	return err
}

const findAPIKeyByPrefix = `-- name: FindAPIKeyByPrefix :one
SELECT id, name, prefix, key_hash, scopes, webhook_secret_ciphertext, created_by, last_used_at, revoked_at, created_at FROM api_keys WHERE prefix=$1
`

func (q *Queries) FindAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, findAPIKeyByPrefix, prefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.WebhookSecretCiphertext,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findRefreshToken = `-- name: FindRefreshToken :one
SELECT id, user_id, family_id, token_hash, expires_at, revoked_at, replaced_by, created_at FROM refresh_tokens WHERE token_hash=$1
`

func (q *Queries) FindRefreshToken(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, findRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, password_hash, name, role, status, must_change_password, last_login_at, created_at FROM users WHERE lower(email)=lower($1)
`

func (q *Queries) FindUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, name, prefix, key_hash, scopes, webhook_secret_ciphertext, created_by, last_used_at, revoked_at, created_at FROM api_keys WHERE id=$1
`

func (q *Queries) GetAPIKey(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.WebhookSecretCiphertext,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT id, user_id, family_id, token_hash, expires_at, revoked_at, replaced_by, created_at FROM refresh_tokens WHERE id=$1 FOR UPDATE
`

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, id pgtype.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, name, role, status, must_change_password, last_login_at, created_at FROM users WHERE id=$1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, email, password_hash, name, role, status, must_change_password, last_login_at, created_at FROM users WHERE id=$1 FOR UPDATE
`

func (q *Queries) GetUserForUpdate(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, prefix, key_hash, scopes, webhook_secret_ciphertext, created_by, last_used_at, revoked_at, created_at FROM api_keys WHERE ($2::timestamptz IS NULL OR (created_at,id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC,id DESC LIMIT $1
`

type ListAPIKeysParams struct {
	Limit      int32              `json:"limit"`
	BeforeTime pgtype.Timestamptz `json:"before_time"`
	BeforeID   pgtype.UUID        `json:"before_id"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, arg.Limit, arg.BeforeTime, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.KeyHash,
			&i.Scopes,
			&i.WebhookSecretCiphertext,
			&i.CreatedBy,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, name, role, status, must_change_password, last_login_at, created_at FROM users WHERE ($2::timestamptz IS NULL OR (created_at,id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC,id DESC LIMIT $1
`

type ListUsersParams struct {
	Limit      int32              `json:"limit"`
	BeforeTime pgtype.Timestamptz `json:"before_time"`
	BeforeID   pgtype.UUID        `json:"before_id"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.BeforeTime, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Role,
			&i.Status,
			&i.MustChangePassword,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIdentity = `-- name: LockIdentity :exec
SELECT pg_advisory_xact_lock(724391820)
`

func (q *Queries) LockIdentity(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockIdentity)
	return err
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at=coalesce(revoked_at,$2) WHERE id=$1
`

type RevokeAPIKeyParams struct {
	ID        pgtype.UUID        `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :execrows
UPDATE refresh_tokens SET revoked_at=coalesce(revoked_at,$2) WHERE family_id=$1
`

type RevokeRefreshFamilyParams struct {
	FamilyID  pgtype.UUID        `json:"family_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeRefreshFamily(ctx context.Context, arg RevokeRefreshFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshFamily, arg.FamilyID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserRefreshTokens = `-- name: RevokeUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at=coalesce(revoked_at,$1) WHERE user_id=$2
AND ($3::uuid='00000000-0000-0000-0000-000000000000'::uuid OR family_id<>$3)
`

type RevokeUserRefreshTokensParams struct {
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	UserID       pgtype.UUID        `json:"user_id"`
	ExceptFamily pgtype.UUID        `json:"except_family"`
}

func (q *Queries) RevokeUserRefreshTokens(ctx context.Context, arg RevokeUserRefreshTokensParams) error {
	_, err := q.db.Exec(ctx, revokeUserRefreshTokens, arg.RevokedAt, arg.UserID, arg.ExceptFamily)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :execrows
UPDATE refresh_tokens SET replaced_by=$2,revoked_at=$3 WHERE id=$1 AND revoked_at IS NULL
`

type RotateRefreshTokenParams struct {
	ID         pgtype.UUID        `json:"id"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateRefreshToken, arg.ID, arg.ReplacedBy, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPassword = `-- name: SetPassword :execrows
UPDATE users SET password_hash=$2,must_change_password=false WHERE id=$1
`

type SetPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKey = `-- name: TouchAPIKey :execrows
UPDATE api_keys SET last_used_at=$2
WHERE id=$1 AND (last_used_at IS NULL OR last_used_at < $2::timestamptz - interval '1 minute')
`

type TouchAPIKeyParams struct {
	ID         pgtype.UUID        `json:"id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchAPIKey, arg.ID, arg.LastUsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchLastLogin = `-- name: TouchLastLogin :execrows
UPDATE users SET last_login_at=$2 WHERE id=$1
`

type TouchLastLoginParams struct {
	ID          pgtype.UUID        `json:"id"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) TouchLastLogin(ctx context.Context, arg TouchLastLoginParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchLastLogin, arg.ID, arg.LastLoginAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE users SET name=coalesce($2::text,name),role=coalesce($3::text,role),status=coalesce($4::text,status)
WHERE id=$1 RETURNING id, email, password_hash, name, role, status, must_change_password, last_login_at, created_at
`

type UpdateMemberParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   pgtype.Text `json:"name"`
	Role   pgtype.Text `json:"role"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (User, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}
