// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	Description         string             `json:"description"`
	ProviderID          pgtype.UUID        `json:"provider_id"`
	Model               string             `json:"model"`
	SystemPrompt        string             `json:"system_prompt"`
	Temperature         pgtype.Float8      `json:"temperature"`
	MaxOutputTokens     pgtype.Int4        `json:"max_output_tokens"`
	MaxIterations       int32              `json:"max_iterations"`
	TimeoutSeconds      int32              `json:"timeout_seconds"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	ArchivedAt          pgtype.Timestamptz `json:"archived_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ContextWindowTokens int32              `json:"context_window_tokens"`
}

type AgentMcpServer struct {
	AgentID     pgtype.UUID `json:"agent_id"`
	McpServerID pgtype.UUID `json:"mcp_server_id"`
}

type AgentSkill struct {
	AgentID pgtype.UUID `json:"agent_id"`
	SkillID pgtype.UUID `json:"skill_id"`
}

type AgentTool struct {
	AgentID pgtype.UUID `json:"agent_id"`
	ToolID  pgtype.UUID `json:"tool_id"`
}

type ApiConnection struct {
	ID                      pgtype.UUID        `json:"id"`
	Slug                    string             `json:"slug"`
	DisplayName             string             `json:"display_name"`
	BaseUrl                 string             `json:"base_url"`
	PublicHeaders           []byte             `json:"public_headers"`
	SecretHeadersCiphertext []byte             `json:"secret_headers_ciphertext"`
	SecretHeaderNames       []string           `json:"secret_header_names"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type ApiKey struct {
	ID                      pgtype.UUID        `json:"id"`
	Name                    string             `json:"name"`
	Prefix                  string             `json:"prefix"`
	KeyHash                 []byte             `json:"key_hash"`
	Scopes                  []string           `json:"scopes"`
	WebhookSecretCiphertext []byte             `json:"webhook_secret_ciphertext"`
	CreatedBy               pgtype.UUID        `json:"created_by"`
	LastUsedAt              pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt               pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type IdempotencyKey struct {
	PrincipalKind  string             `json:"principal_kind"`
	PrincipalID    pgtype.UUID        `json:"principal_id"`
	Key            string             `json:"key"`
	RequestHash    []byte             `json:"request_hash"`
	RunID          pgtype.UUID        `json:"run_id"`
	ResponseStatus int32              `json:"response_status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type LlmProvider struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Kind             string             `json:"kind"`
	BaseUrl          pgtype.Text        `json:"base_url"`
	ApiKeyCiphertext []byte             `json:"api_key_ciphertext"`
	ApiKeyHint       pgtype.Text        `json:"api_key_hint"`
	DefaultModel     pgtype.Text        `json:"default_model"`
	Status           string             `json:"status"`
	LastError        []byte             `json:"last_error"`
	LastCheckedAt    pgtype.Timestamptz `json:"last_checked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Revision         int64              `json:"revision"`
}

type McpServer struct {
	ID                      pgtype.UUID        `json:"id"`
	Slug                    string             `json:"slug"`
	DisplayName             string             `json:"display_name"`
	Url                     string             `json:"url"`
	SecretHeadersCiphertext []byte             `json:"secret_headers_ciphertext"`
	SecretHeaderNames       []string           `json:"secret_header_names"`
	AllowedTools            []string           `json:"allowed_tools"`
	ToolsCache              []byte             `json:"tools_cache"`
	Status                  string             `json:"status"`
	LastError               []byte             `json:"last_error"`
	LastSyncedAt            pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	Revision                int64              `json:"revision"`
}

type Message struct {
	ID           pgtype.UUID        `json:"id"`
	SessionID    pgtype.UUID        `json:"session_id"`
	RunID        pgtype.UUID        `json:"run_id"`
	Seq          int64              `json:"seq"`
	Role         string             `json:"role"`
	Content      string             `json:"content"`
	ToolCalls    []byte             `json:"tool_calls"`
	ToolCallID   pgtype.Text        `json:"tool_call_id"`
	ToolName     pgtype.Text        `json:"tool_name"`
	ProviderMeta []byte             `json:"provider_meta"`
	IsError      bool               `json:"is_error"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	FamilyID   pgtype.UUID        `json:"family_id"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Run struct {
	ID                  pgtype.UUID        `json:"id"`
	AgentID             pgtype.UUID        `json:"agent_id"`
	SessionID           pgtype.UUID        `json:"session_id"`
	Mode                string             `json:"mode"`
	Status              string             `json:"status"`
	Source              string             `json:"source"`
	TriggeredByUserID   pgtype.UUID        `json:"triggered_by_user_id"`
	TriggeredByApiKeyID pgtype.UUID        `json:"triggered_by_api_key_id"`
	Input               []byte             `json:"input"`
	Output              pgtype.Text        `json:"output"`
	ErrorCode           pgtype.Text        `json:"error_code"`
	ErrorMessage        pgtype.Text        `json:"error_message"`
	Iterations          int32              `json:"iterations"`
	InputTokens         pgtype.Int8        `json:"input_tokens"`
	OutputTokens        pgtype.Int8        `json:"output_tokens"`
	Metadata            []byte             `json:"metadata"`
	CancelRequestedAt   pgtype.Timestamptz `json:"cancel_requested_at"`
	QueuedAt            pgtype.Timestamptz `json:"queued_at"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	FinishedAt          pgtype.Timestamptz `json:"finished_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	WebhookUrl          pgtype.Text        `json:"webhook_url"`
}

type RunJob struct {
	RunID       pgtype.UUID        `json:"run_id"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	LockedBy    pgtype.Text        `json:"locked_by"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
	Attempts    int32              `json:"attempts"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID                        pgtype.UUID        `json:"id"`
	AgentID                   pgtype.UUID        `json:"agent_id"`
	Source                    string             `json:"source"`
	CreatedByUserID           pgtype.UUID        `json:"created_by_user_id"`
	CreatedByApiKeyID         pgtype.UUID        `json:"created_by_api_key_id"`
	ExternalKey               pgtype.Text        `json:"external_key"`
	Title                     string             `json:"title"`
	NextMessageSeq            int64              `json:"next_message_seq"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	LastPromptEstimatedTokens pgtype.Int8        `json:"last_prompt_estimated_tokens"`
	LastPromptTokens          pgtype.Int8        `json:"last_prompt_tokens"`
}

type SessionContextSnapshot struct {
	ID                pgtype.UUID        `json:"id"`
	SessionID         pgtype.UUID        `json:"session_id"`
	SourceRunID       pgtype.UUID        `json:"source_run_id"`
	Version           int64              `json:"version"`
	CoveredThroughSeq int64              `json:"covered_through_seq"`
	Summary           string             `json:"summary"`
	InputTokens       pgtype.Int8        `json:"input_tokens"`
	OutputTokens      pgtype.Int8        `json:"output_tokens"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Skill struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	SourceType     string             `json:"source_type"`
	SourceFilename string             `json:"source_filename"`
	Content        string             `json:"content"`
	Checksum       string             `json:"checksum"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Span struct {
	ID           pgtype.UUID        `json:"id"`
	RunID        pgtype.UUID        `json:"run_id"`
	ParentSpanID pgtype.UUID        `json:"parent_span_id"`
	Kind         string             `json:"kind"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	Model        pgtype.Text        `json:"model"`
	ToolName     pgtype.Text        `json:"tool_name"`
	InputTokens  pgtype.Int8        `json:"input_tokens"`
	OutputTokens pgtype.Int8        `json:"output_tokens"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	EndedAt      pgtype.Timestamptz `json:"ended_at"`
	DurationMs   int64              `json:"duration_ms"`
	Attributes   []byte             `json:"attributes"`
	ErrorMessage pgtype.Text        `json:"error_message"`
}

type Tool struct {
	ID                      pgtype.UUID        `json:"id"`
	Slug                    string             `json:"slug"`
	DisplayName             string             `json:"display_name"`
	Description             string             `json:"description"`
	Kind                    string             `json:"kind"`
	Method                  string             `json:"method"`
	UrlTemplate             string             `json:"url_template"`
	Params                  []byte             `json:"params"`
	PublicHeaders           []byte             `json:"public_headers"`
	SecretHeadersCiphertext []byte             `json:"secret_headers_ciphertext"`
	SecretHeaderNames       []string           `json:"secret_header_names"`
	TimeoutSeconds          int32              `json:"timeout_seconds"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	ConnectionID            pgtype.UUID        `json:"connection_id"`
}

type User struct {
	ID                 pgtype.UUID        `json:"id"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	Name               string             `json:"name"`
	Role               string             `json:"role"`
	Status             string             `json:"status"`
	MustChangePassword bool               `json:"must_change_password"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type WebhookDelivery struct {
	ID             pgtype.UUID        `json:"id"`
	RunID          pgtype.UUID        `json:"run_id"`
	ApiKeyID       pgtype.UUID        `json:"api_key_id"`
	Url            string             `json:"url"`
	Event          string             `json:"event"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	LastStatusCode pgtype.Int4        `json:"last_status_code"`
	LastError      pgtype.Text        `json:"last_error"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
