// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const overviewDaily = `-- name: OverviewDaily :many
SELECT day::date AS day,
       COALESCE(counted.playground,0)::bigint AS playground,
       COALESCE(counted.api,0)::bigint AS api,
       COALESCE(counted.failed,0)::bigint AS failed
FROM generate_series(
       date_trunc('day',$2::timestamptz AT TIME ZONE $1::text),
       date_trunc('day',($3::timestamptz - interval '1 microsecond') AT TIME ZONE $1::text),
       interval '1 day'
     ) AS day
LEFT JOIN (
  SELECT date_trunc('day',created_at AT TIME ZONE $1::text) AS bucket,
         COUNT(*) FILTER (WHERE source='playground') AS playground,
         COUNT(*) FILTER (WHERE source='api') AS api,
         COUNT(*) FILTER (WHERE status='failed') AS failed
  FROM runs
  WHERE created_at >= $2 AND created_at < $3
  GROUP BY bucket
) AS counted ON counted.bucket=day
ORDER BY day
`

type OverviewDailyParams struct {
	TimeZone string             `json:"time_zone"`
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type OverviewDailyRow struct {
	Day        pgtype.Date `json:"day"`
	Playground int64       `json:"playground"`
	Api        int64       `json:"api"`
	Failed     int64       `json:"failed"`
}

// Every day in the range gets a row, including days without any request, so the
// trend chart cannot silently drop quiet days and distort the shape.
func (q *Queries) OverviewDaily(ctx context.Context, arg OverviewDailyParams) ([]OverviewDailyRow, error) {
	rows, err := q.db.Query(ctx, overviewDaily, arg.TimeZone, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OverviewDailyRow{}
	for rows.Next() {
		var i OverviewDailyRow
		if err := rows.Scan(
			&i.Day,
			&i.Playground,
			&i.Api,
			&i.Failed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overviewStepLimitHits = `-- name: OverviewStepLimitHits :one
SELECT COUNT(*) AS hits
FROM runs JOIN agents ON agents.id=runs.agent_id
WHERE runs.created_at >= $1 AND runs.created_at < $2
  AND runs.iterations >= agents.max_iterations
`

type OverviewStepLimitHitsParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

func (q *Queries) OverviewStepLimitHits(ctx context.Context, arg OverviewStepLimitHitsParams) (int64, error) {
	row := q.db.QueryRow(ctx, overviewStepLimitHits, arg.FromTime, arg.ToTime)
	var hits int64
	err := row.Scan(&hits)
	return hits, err
}

const overviewTopAgents = `-- name: OverviewTopAgents :many
SELECT runs.agent_id,
       agents.name AS agent_name,
       COUNT(*) AS requests,
       COUNT(*) FILTER (WHERE runs.status='succeeded') AS succeeded,
       COUNT(*) FILTER (WHERE runs.status='failed') AS failed,
       COUNT(*) FILTER (WHERE runs.started_at IS NOT NULL AND runs.finished_at IS NOT NULL) AS finished,
       COALESCE(PERCENTILE_CONT(0.95) WITHIN GROUP (
         ORDER BY EXTRACT(EPOCH FROM (runs.finished_at-runs.started_at))*1000
       ),0)::double precision AS p95_duration_ms,
       COALESCE(SUM(COALESCE(runs.input_tokens,0)+COALESCE(runs.output_tokens,0)),0)::bigint AS processing_units
FROM runs JOIN agents ON agents.id=runs.agent_id
WHERE runs.created_at >= $1 AND runs.created_at < $2
GROUP BY runs.agent_id,agents.name
ORDER BY requests DESC,agents.name ASC
LIMIT $3
`

type OverviewTopAgentsParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
	RowLimit int32              `json:"row_limit"`
}

type OverviewTopAgentsRow struct {
	AgentID         pgtype.UUID `json:"agent_id"`
	AgentName       string      `json:"agent_name"`
	Requests        int64       `json:"requests"`
	Succeeded       int64       `json:"succeeded"`
	Failed          int64       `json:"failed"`
	Finished        int64       `json:"finished"`
	P95DurationMs   float64     `json:"p95_duration_ms"`
	ProcessingUnits int64       `json:"processing_units"`
}

func (q *Queries) OverviewTopAgents(ctx context.Context, arg OverviewTopAgentsParams) ([]OverviewTopAgentsRow, error) {
	rows, err := q.db.Query(ctx, overviewTopAgents, arg.FromTime, arg.ToTime, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OverviewTopAgentsRow{}
	for rows.Next() {
		var i OverviewTopAgentsRow
		if err := rows.Scan(
			&i.AgentID,
			&i.AgentName,
			&i.Requests,
			&i.Succeeded,
			&i.Failed,
			&i.Finished,
			&i.P95DurationMs,
			&i.ProcessingUnits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overviewTopErrors = `-- name: OverviewTopErrors :many
SELECT error_code::text AS error_code,
       COUNT(*) AS occurrences,
       MAX(created_at)::timestamptz AS last_seen_at,
       ((ARRAY_AGG(id ORDER BY created_at DESC))[1])::uuid AS sample_run_id
FROM runs
WHERE created_at >= $1 AND created_at < $2
  AND error_code IS NOT NULL
GROUP BY error_code
ORDER BY occurrences DESC,error_code ASC
LIMIT $3
`

type OverviewTopErrorsParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
	RowLimit int32              `json:"row_limit"`
}

type OverviewTopErrorsRow struct {
	ErrorCode   string             `json:"error_code"`
	Occurrences int64              `json:"occurrences"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	SampleRunID pgtype.UUID        `json:"sample_run_id"`
}

func (q *Queries) OverviewTopErrors(ctx context.Context, arg OverviewTopErrorsParams) ([]OverviewTopErrorsRow, error) {
	rows, err := q.db.Query(ctx, overviewTopErrors, arg.FromTime, arg.ToTime, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OverviewTopErrorsRow{}
	for rows.Next() {
		var i OverviewTopErrorsRow
		if err := rows.Scan(
			&i.ErrorCode,
			&i.Occurrences,
			&i.LastSeenAt,
			&i.SampleRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overviewTopTools = `-- name: OverviewTopTools :many
SELECT spans.tool_name::text AS tool_name,
       COUNT(*) AS calls,
       COUNT(*) FILTER (WHERE spans.status='error') AS errors,
       COALESCE(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY spans.duration_ms),0)::double precision AS p95_duration_ms
FROM spans JOIN runs ON runs.id=spans.run_id
WHERE spans.kind='tool_call' AND spans.tool_name IS NOT NULL
  AND runs.created_at >= $1 AND runs.created_at < $2
GROUP BY spans.tool_name
ORDER BY calls DESC,tool_name ASC
LIMIT $3
`

type OverviewTopToolsParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
	RowLimit int32              `json:"row_limit"`
}

type OverviewTopToolsRow struct {
	ToolName      string  `json:"tool_name"`
	Calls         int64   `json:"calls"`
	Errors        int64   `json:"errors"`
	P95DurationMs float64 `json:"p95_duration_ms"`
}

// Scoped by the run's created_at, like every other figure on the report, so
// "this period" means the same thing in each block. Filtering on the span's own
// start time would pull in calls from runs the rest of the report excludes.
func (q *Queries) OverviewTopTools(ctx context.Context, arg OverviewTopToolsParams) ([]OverviewTopToolsRow, error) {
	rows, err := q.db.Query(ctx, overviewTopTools, arg.FromTime, arg.ToTime, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OverviewTopToolsRow{}
	for rows.Next() {
		var i OverviewTopToolsRow
		if err := rows.Scan(
			&i.ToolName,
			&i.Calls,
			&i.Errors,
			&i.P95DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overviewTotals = `-- name: OverviewTotals :one
SELECT COUNT(*) AS requests,
       COUNT(*) FILTER (WHERE status='succeeded') AS succeeded,
       COUNT(*) FILTER (WHERE status='failed') AS failed,
       COUNT(*) FILTER (WHERE status='cancelled') AS cancelled,
       COUNT(DISTINCT session_id) AS sessions,
       COUNT(*) FILTER (WHERE started_at IS NOT NULL AND finished_at IS NOT NULL) AS finished,
       COALESCE(AVG(EXTRACT(EPOCH FROM (finished_at-started_at))*1000),0)::double precision AS avg_duration_ms,
       COALESCE(PERCENTILE_CONT(0.95) WITHIN GROUP (
         ORDER BY EXTRACT(EPOCH FROM (finished_at-started_at))*1000
       ),0)::double precision AS p95_duration_ms,
       COALESCE(SUM(COALESCE(input_tokens,0)+COALESCE(output_tokens,0)),0)::bigint AS processing_units
FROM runs
WHERE created_at >= $1 AND created_at < $2
`

type OverviewTotalsParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type OverviewTotalsRow struct {
	Requests        int64   `json:"requests"`
	Succeeded       int64   `json:"succeeded"`
	Failed          int64   `json:"failed"`
	Cancelled       int64   `json:"cancelled"`
	Sessions        int64   `json:"sessions"`
	Finished        int64   `json:"finished"`
	AvgDurationMs   float64 `json:"avg_duration_ms"`
	P95DurationMs   float64 `json:"p95_duration_ms"`
	ProcessingUnits int64   `json:"processing_units"`
}

func (q *Queries) OverviewTotals(ctx context.Context, arg OverviewTotalsParams) (OverviewTotalsRow, error) {
	row := q.db.QueryRow(ctx, overviewTotals, arg.FromTime, arg.ToTime)
	var i OverviewTotalsRow
	err := row.Scan(
		&i.Requests,
		&i.Succeeded,
		&i.Failed,
		&i.Cancelled,
		&i.Sessions,
		&i.Finished,
		&i.AvgDurationMs,
		&i.P95DurationMs,
		&i.ProcessingUnits,
	)
	return i, err
}
