// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendMessage = `-- name: AppendMessage :one
WITH next AS (
  UPDATE sessions
  SET next_message_seq=next_message_seq+1,updated_at=GREATEST(updated_at,$11)
  WHERE id=$2 AND deleted_at IS NULL
  RETURNING next_message_seq-1 AS seq
)
INSERT INTO messages (
  id,session_id,run_id,seq,role,content,tool_calls,tool_call_id,tool_name,provider_meta,is_error,created_at
)
SELECT $1,$2,$3,next.seq,$4,$5,
       $6,$7,$8,$9,
       $10,$11
FROM next
RETURNING id, session_id, run_id, seq, role, content, tool_calls, tool_call_id, tool_name, provider_meta, is_error, created_at
`

type AppendMessageParams struct {
	ID           pgtype.UUID        `json:"id"`
	SessionID    pgtype.UUID        `json:"session_id"`
	RunID        pgtype.UUID        `json:"run_id"`
	Role         string             `json:"role"`
	Content      string             `json:"content"`
	ToolCalls    []byte             `json:"tool_calls"`
	ToolCallID   pgtype.Text        `json:"tool_call_id"`
	ToolName     pgtype.Text        `json:"tool_name"`
	ProviderMeta []byte             `json:"provider_meta"`
	IsError      bool               `json:"is_error"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AppendMessage(ctx context.Context, arg AppendMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, appendMessage,
		arg.ID,
		arg.SessionID,
		arg.RunID,
		arg.Role,
		arg.Content,
		arg.ToolCalls,
		arg.ToolCallID,
		arg.ToolName,
		arg.ProviderMeta,
		arg.IsError,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.Seq,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.ToolName,
		&i.ProviderMeta,
		&i.IsError,
		&i.CreatedAt,
	)
	return i, err
}

const createContextSnapshotCAS = `-- name: CreateContextSnapshotCAS :execrows
INSERT INTO session_context_snapshots (
  id,session_id,source_run_id,version,covered_through_seq,summary,input_tokens,output_tokens,created_at
)
SELECT $1,$2,$3,$4,
       $5,$6,$7,
       $8,$9
WHERE COALESCE((
  SELECT MAX(snapshot.version) FROM session_context_snapshots AS snapshot
  WHERE snapshot.session_id=$2
),0)=$10
  AND COALESCE((
    SELECT MAX(snapshot.covered_through_seq) FROM session_context_snapshots AS snapshot
    WHERE snapshot.session_id=$2
  ),0) < $5
ON CONFLICT DO NOTHING
`

type CreateContextSnapshotCASParams struct {
	ID                pgtype.UUID        `json:"id"`
	SessionID         pgtype.UUID        `json:"session_id"`
	SourceRunID       pgtype.UUID        `json:"source_run_id"`
	Version           int64              `json:"version"`
	CoveredThroughSeq int64              `json:"covered_through_seq"`
	Summary           string             `json:"summary"`
	InputTokens       pgtype.Int8        `json:"input_tokens"`
	OutputTokens      pgtype.Int8        `json:"output_tokens"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ExpectedVersion   int64              `json:"expected_version"`
}

func (q *Queries) CreateContextSnapshotCAS(ctx context.Context, arg CreateContextSnapshotCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, createContextSnapshotCAS,
		arg.ID,
		arg.SessionID,
		arg.SourceRunID,
		arg.Version,
		arg.CoveredThroughSeq,
		arg.Summary,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CreatedAt,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRun = `-- name: CreateRun :exec
INSERT INTO runs (
  id,agent_id,session_id,mode,status,source,triggered_by_user_id,triggered_by_api_key_id,input,output,
  error_code,error_message,iterations,input_tokens,output_tokens,metadata,cancel_requested_at,queued_at,
  started_at,finished_at,created_at,webhook_url
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22)
`

type CreateRunParams struct {
	ID                  pgtype.UUID        `json:"id"`
	AgentID             pgtype.UUID        `json:"agent_id"`
	SessionID           pgtype.UUID        `json:"session_id"`
	Mode                string             `json:"mode"`
	Status              string             `json:"status"`
	Source              string             `json:"source"`
	TriggeredByUserID   pgtype.UUID        `json:"triggered_by_user_id"`
	TriggeredByApiKeyID pgtype.UUID        `json:"triggered_by_api_key_id"`
	Input               []byte             `json:"input"`
	Output              pgtype.Text        `json:"output"`
	ErrorCode           pgtype.Text        `json:"error_code"`
	ErrorMessage        pgtype.Text        `json:"error_message"`
	Iterations          int32              `json:"iterations"`
	InputTokens         pgtype.Int8        `json:"input_tokens"`
	OutputTokens        pgtype.Int8        `json:"output_tokens"`
	Metadata            []byte             `json:"metadata"`
	CancelRequestedAt   pgtype.Timestamptz `json:"cancel_requested_at"`
	QueuedAt            pgtype.Timestamptz `json:"queued_at"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	FinishedAt          pgtype.Timestamptz `json:"finished_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	WebhookUrl          pgtype.Text        `json:"webhook_url"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.Exec(ctx, createRun,
		arg.ID,
		arg.AgentID,
		arg.SessionID,
		arg.Mode,
		arg.Status,
		arg.Source,
		arg.TriggeredByUserID,
		arg.TriggeredByApiKeyID,
		arg.Input,
		arg.Output,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Iterations,
		arg.InputTokens,
		arg.OutputTokens,
		arg.Metadata,
		arg.CancelRequestedAt,
		arg.QueuedAt,
		arg.StartedAt,
		arg.FinishedAt,
		arg.CreatedAt,
		arg.WebhookUrl,
	)
	return err
}

const createSession = `-- name: CreateSession :execrows
INSERT INTO sessions (
  id,agent_id,source,created_by_user_id,created_by_api_key_id,external_key,title,created_at,updated_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
ON CONFLICT (created_by_api_key_id,external_key) WHERE deleted_at IS NULL DO NOTHING
`

type CreateSessionParams struct {
	ID                pgtype.UUID        `json:"id"`
	AgentID           pgtype.UUID        `json:"agent_id"`
	Source            string             `json:"source"`
	CreatedByUserID   pgtype.UUID        `json:"created_by_user_id"`
	CreatedByApiKeyID pgtype.UUID        `json:"created_by_api_key_id"`
	ExternalKey       pgtype.Text        `json:"external_key"`
	Title             string             `json:"title"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.AgentID,
		arg.Source,
		arg.CreatedByUserID,
		arg.CreatedByApiKeyID,
		arg.ExternalKey,
		arg.Title,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSpan = `-- name: CreateSpan :exec
INSERT INTO spans (
  id,run_id,parent_span_id,kind,name,status,model,tool_name,input_tokens,output_tokens,started_at,ended_at,
  duration_ms,attributes,error_message
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
`

type CreateSpanParams struct {
	ID           pgtype.UUID        `json:"id"`
	RunID        pgtype.UUID        `json:"run_id"`
	ParentSpanID pgtype.UUID        `json:"parent_span_id"`
	Kind         string             `json:"kind"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	Model        pgtype.Text        `json:"model"`
	ToolName     pgtype.Text        `json:"tool_name"`
	InputTokens  pgtype.Int8        `json:"input_tokens"`
	OutputTokens pgtype.Int8        `json:"output_tokens"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	EndedAt      pgtype.Timestamptz `json:"ended_at"`
	DurationMs   int64              `json:"duration_ms"`
	Attributes   []byte             `json:"attributes"`
	ErrorMessage pgtype.Text        `json:"error_message"`
}

func (q *Queries) CreateSpan(ctx context.Context, arg CreateSpanParams) error {
	_, err := q.db.Exec(ctx, createSpan,
		arg.ID,
		arg.RunID,
		arg.ParentSpanID,
		arg.Kind,
		arg.Name,
		arg.Status,
		arg.Model,
		arg.ToolName,
		arg.InputTokens,
		arg.OutputTokens,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationMs,
		arg.Attributes,
		arg.ErrorMessage,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :execrows
UPDATE sessions SET deleted_at=$2,updated_at=$2 WHERE id=$1 AND deleted_at IS NULL
`

type DeleteSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishRun = `-- name: FinishRun :one
UPDATE runs SET status=$2,output=$3,error_code=$4,error_message=$5,iterations=$6,input_tokens=$7,
  output_tokens=$8,finished_at=$9
WHERE id=$1 AND status IN ('queued','running')
RETURNING id, agent_id, session_id, mode, status, source, triggered_by_user_id, triggered_by_api_key_id, input, output, error_code, error_message, iterations, input_tokens, output_tokens, metadata, cancel_requested_at, queued_at, started_at, finished_at, created_at, webhook_url
`

type FinishRunParams struct {
	ID           pgtype.UUID        `json:"id"`
	Status       string             `json:"status"`
	Output       pgtype.Text        `json:"output"`
	ErrorCode    pgtype.Text        `json:"error_code"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	Iterations   int32              `json:"iterations"`
	InputTokens  pgtype.Int8        `json:"input_tokens"`
	OutputTokens pgtype.Int8        `json:"output_tokens"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, finishRun,
		arg.ID,
		arg.Status,
		arg.Output,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Iterations,
		arg.InputTokens,
		arg.OutputTokens,
		arg.FinishedAt,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.SessionID,
		&i.Mode,
		&i.Status,
		&i.Source,
		&i.TriggeredByUserID,
		&i.TriggeredByApiKeyID,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Iterations,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Metadata,
		&i.CancelRequestedAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.WebhookUrl,
	)
	return i, err
}

const getLatestContextSnapshot = `-- name: GetLatestContextSnapshot :one
SELECT id, session_id, source_run_id, version, covered_through_seq, summary, input_tokens, output_tokens, created_at FROM session_context_snapshots
WHERE session_id=$1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestContextSnapshot(ctx context.Context, sessionID pgtype.UUID) (SessionContextSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestContextSnapshot, sessionID)
	var i SessionContextSnapshot
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SourceRunID,
		&i.Version,
		&i.CoveredThroughSeq,
		&i.Summary,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, agent_id, session_id, mode, status, source, triggered_by_user_id, triggered_by_api_key_id, input, output, error_code, error_message, iterations, input_tokens, output_tokens, metadata, cancel_requested_at, queued_at, started_at, finished_at, created_at, webhook_url FROM runs WHERE id=$1
`

func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.SessionID,
		&i.Mode,
		&i.Status,
		&i.Source,
		&i.TriggeredByUserID,
		&i.TriggeredByApiKeyID,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Iterations,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Metadata,
		&i.CancelRequestedAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.WebhookUrl,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, agent_id, source, created_by_user_id, created_by_api_key_id, external_key, title, next_message_seq, deleted_at, created_at, updated_at, last_prompt_estimated_tokens, last_prompt_tokens FROM sessions WHERE id=$1 AND deleted_at IS NULL
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Source,
		&i.CreatedByUserID,
		&i.CreatedByApiKeyID,
		&i.ExternalKey,
		&i.Title,
		&i.NextMessageSeq,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPromptEstimatedTokens,
		&i.LastPromptTokens,
	)
	return i, err
}

const getSessionByExternalKey = `-- name: GetSessionByExternalKey :one
SELECT id, agent_id, source, created_by_user_id, created_by_api_key_id, external_key, title, next_message_seq, deleted_at, created_at, updated_at, last_prompt_estimated_tokens, last_prompt_tokens FROM sessions
WHERE created_by_api_key_id=$1 AND external_key=$2 AND deleted_at IS NULL
FOR UPDATE
`

type GetSessionByExternalKeyParams struct {
	CreatedByApiKeyID pgtype.UUID `json:"created_by_api_key_id"`
	ExternalKey       pgtype.Text `json:"external_key"`
}

func (q *Queries) GetSessionByExternalKey(ctx context.Context, arg GetSessionByExternalKeyParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByExternalKey, arg.CreatedByApiKeyID, arg.ExternalKey)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Source,
		&i.CreatedByUserID,
		&i.CreatedByApiKeyID,
		&i.ExternalKey,
		&i.Title,
		&i.NextMessageSeq,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPromptEstimatedTokens,
		&i.LastPromptTokens,
	)
	return i, err
}

const getSessionForUpdate = `-- name: GetSessionForUpdate :one
SELECT id, agent_id, source, created_by_user_id, created_by_api_key_id, external_key, title, next_message_seq, deleted_at, created_at, updated_at, last_prompt_estimated_tokens, last_prompt_tokens FROM sessions WHERE id=$1 AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) GetSessionForUpdate(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionForUpdate, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Source,
		&i.CreatedByUserID,
		&i.CreatedByApiKeyID,
		&i.ExternalKey,
		&i.Title,
		&i.NextMessageSeq,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPromptEstimatedTokens,
		&i.LastPromptTokens,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, session_id, run_id, seq, role, content, tool_calls, tool_call_id, tool_name, provider_meta, is_error, created_at FROM messages
WHERE session_id=$1
  AND ($2::bigint IS NULL OR (seq,id) > ($2,$3::uuid))
ORDER BY seq,id LIMIT $4
`

type ListMessagesParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	AfterSeq  pgtype.Int8 `json:"after_seq"`
	AfterID   pgtype.UUID `json:"after_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages,
		arg.SessionID,
		arg.AfterSeq,
		arg.AfterID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RunID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolCallID,
			&i.ToolName,
			&i.ProviderMeta,
			&i.IsError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesAfterSeq = `-- name: ListMessagesAfterSeq :many
SELECT id, session_id, run_id, seq, role, content, tool_calls, tool_call_id, tool_name, provider_meta, is_error, created_at FROM messages
WHERE session_id=$1 AND seq > $2
ORDER BY seq,id LIMIT $3
`

type ListMessagesAfterSeqParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	AfterSeq  int64       `json:"after_seq"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListMessagesAfterSeq(ctx context.Context, arg ListMessagesAfterSeqParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesAfterSeq, arg.SessionID, arg.AfterSeq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RunID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolCallID,
			&i.ToolName,
			&i.ProviderMeta,
			&i.IsError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMessages = `-- name: ListRecentMessages :many
SELECT id, session_id, run_id, seq, role, content, tool_calls, tool_call_id, tool_name, provider_meta, is_error, created_at FROM (
  SELECT id, session_id, run_id, seq, role, content, tool_calls, tool_call_id, tool_name, provider_meta, is_error, created_at FROM messages WHERE session_id=$1 ORDER BY seq DESC,id DESC LIMIT $2
) recent ORDER BY seq,id
`

type ListRecentMessagesParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListRecentMessages(ctx context.Context, arg ListRecentMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listRecentMessages, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RunID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolCallID,
			&i.ToolName,
			&i.ProviderMeta,
			&i.IsError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunMessages = `-- name: ListRunMessages :many
SELECT id, session_id, run_id, seq, role, content, tool_calls, tool_call_id, tool_name, provider_meta, is_error, created_at FROM messages
WHERE session_id=$1
  AND run_id=$2
  AND ($3::bigint IS NULL OR (seq,id) > ($3,$4::uuid))
ORDER BY seq,id LIMIT $5
`

type ListRunMessagesParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	RunID     pgtype.UUID `json:"run_id"`
	AfterSeq  pgtype.Int8 `json:"after_seq"`
	AfterID   pgtype.UUID `json:"after_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListRunMessages(ctx context.Context, arg ListRunMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listRunMessages,
		arg.SessionID,
		arg.RunID,
		arg.AfterSeq,
		arg.AfterID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RunID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolCallID,
			&i.ToolName,
			&i.ProviderMeta,
			&i.IsError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, agent_id, session_id, mode, status, source, triggered_by_user_id, triggered_by_api_key_id, input, output, error_code, error_message, iterations, input_tokens, output_tokens, metadata, cancel_requested_at, queued_at, started_at, finished_at, created_at, webhook_url FROM runs
WHERE ($1::uuid IS NULL OR agent_id=$1)
  AND ($2::text IS NULL OR status=$2)
  AND ($3::text IS NULL OR source=$3)
  AND ($4::timestamptz IS NULL OR created_at >= $4)
  AND ($5::timestamptz IS NULL OR created_at < $5)
  AND ($6::uuid IS NULL OR triggered_by_user_id=$6)
  AND ($7::uuid IS NULL OR triggered_by_api_key_id=$7)
  AND ($8::timestamptz IS NULL OR (created_at,id) < ($8,$9::uuid))
ORDER BY created_at DESC,id DESC LIMIT $10
`

type ListRunsParams struct {
	AgentID       pgtype.UUID        `json:"agent_id"`
	Status        pgtype.Text        `json:"status"`
	Source        pgtype.Text        `json:"source"`
	FromTime      pgtype.Timestamptz `json:"from_time"`
	ToTime        pgtype.Timestamptz `json:"to_time"`
	OwnerUserID   pgtype.UUID        `json:"owner_user_id"`
	OwnerApiKeyID pgtype.UUID        `json:"owner_api_key_id"`
	BeforeTime    pgtype.Timestamptz `json:"before_time"`
	BeforeID      pgtype.UUID        `json:"before_id"`
	Limit         int32              `json:"limit"`
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRuns,
		arg.AgentID,
		arg.Status,
		arg.Source,
		arg.FromTime,
		arg.ToTime,
		arg.OwnerUserID,
		arg.OwnerApiKeyID,
		arg.BeforeTime,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SessionID,
			&i.Mode,
			&i.Status,
			&i.Source,
			&i.TriggeredByUserID,
			&i.TriggeredByApiKeyID,
			&i.Input,
			&i.Output,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Iterations,
			&i.InputTokens,
			&i.OutputTokens,
			&i.Metadata,
			&i.CancelRequestedAt,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.WebhookUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, agent_id, source, created_by_user_id, created_by_api_key_id, external_key, title, next_message_seq, deleted_at, created_at, updated_at, last_prompt_estimated_tokens, last_prompt_tokens FROM sessions
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR agent_id=$1)
  AND ($2::text IS NULL OR source=$2)
  AND ($3::uuid IS NULL OR created_by_user_id=$3)
  AND ($4::uuid IS NULL OR created_by_api_key_id=$4)
  AND ($5::timestamptz IS NULL OR (created_at,id) < ($5,$6::uuid))
ORDER BY created_at DESC,id DESC LIMIT $7
`

type ListSessionsParams struct {
	AgentID       pgtype.UUID        `json:"agent_id"`
	Source        pgtype.Text        `json:"source"`
	OwnerUserID   pgtype.UUID        `json:"owner_user_id"`
	OwnerApiKeyID pgtype.UUID        `json:"owner_api_key_id"`
	BeforeTime    pgtype.Timestamptz `json:"before_time"`
	BeforeID      pgtype.UUID        `json:"before_id"`
	Limit         int32              `json:"limit"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions,
		arg.AgentID,
		arg.Source,
		arg.OwnerUserID,
		arg.OwnerApiKeyID,
		arg.BeforeTime,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Source,
			&i.CreatedByUserID,
			&i.CreatedByApiKeyID,
			&i.ExternalKey,
			&i.Title,
			&i.NextMessageSeq,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastPromptEstimatedTokens,
			&i.LastPromptTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByUpdatedAt = `-- name: ListSessionsByUpdatedAt :many
SELECT id, agent_id, source, created_by_user_id, created_by_api_key_id, external_key, title, next_message_seq, deleted_at, created_at, updated_at, last_prompt_estimated_tokens, last_prompt_tokens FROM sessions
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR agent_id=$1)
  AND ($2::text IS NULL OR source=$2)
  AND ($3::uuid IS NULL OR created_by_user_id=$3)
  AND ($4::uuid IS NULL OR created_by_api_key_id=$4)
  AND ($5::timestamptz IS NULL OR (updated_at,id) < ($5,$6::uuid))
ORDER BY updated_at DESC,id DESC LIMIT $7
`

type ListSessionsByUpdatedAtParams struct {
	AgentID         pgtype.UUID        `json:"agent_id"`
	Source          pgtype.Text        `json:"source"`
	OwnerUserID     pgtype.UUID        `json:"owner_user_id"`
	OwnerApiKeyID   pgtype.UUID        `json:"owner_api_key_id"`
	BeforeUpdatedAt pgtype.Timestamptz `json:"before_updated_at"`
	BeforeID        pgtype.UUID        `json:"before_id"`
	Limit           int32              `json:"limit"`
}

func (q *Queries) ListSessionsByUpdatedAt(ctx context.Context, arg ListSessionsByUpdatedAtParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUpdatedAt,
		arg.AgentID,
		arg.Source,
		arg.OwnerUserID,
		arg.OwnerApiKeyID,
		arg.BeforeUpdatedAt,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Source,
			&i.CreatedByUserID,
			&i.CreatedByApiKeyID,
			&i.ExternalKey,
			&i.Title,
			&i.NextMessageSeq,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastPromptEstimatedTokens,
			&i.LastPromptTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpans = `-- name: ListSpans :many
SELECT id, run_id, parent_span_id, kind, name, status, model, tool_name, input_tokens, output_tokens, started_at, ended_at, duration_ms, attributes, error_message FROM spans
WHERE run_id=$1
  AND ($2::timestamptz IS NULL OR (started_at,id) > ($2,$3::uuid))
ORDER BY started_at,id LIMIT $4
`

type ListSpansParams struct {
	RunID     pgtype.UUID        `json:"run_id"`
	AfterTime pgtype.Timestamptz `json:"after_time"`
	AfterID   pgtype.UUID        `json:"after_id"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListSpans(ctx context.Context, arg ListSpansParams) ([]Span, error) {
	rows, err := q.db.Query(ctx, listSpans,
		arg.RunID,
		arg.AfterTime,
		arg.AfterID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Span{}
	for rows.Next() {
		var i Span
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ParentSpanID,
			&i.Kind,
			&i.Name,
			&i.Status,
			&i.Model,
			&i.ToolName,
			&i.InputTokens,
			&i.OutputTokens,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMs,
			&i.Attributes,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestRunCancel = `-- name: RequestRunCancel :one
WITH updated AS (
  UPDATE runs AS target SET cancel_requested_at=COALESCE(target.cancel_requested_at,$2)
  WHERE target.id=$1 AND target.status IN ('queued','running')
  RETURNING target.id, target.agent_id, target.session_id, target.mode, target.status, target.source, target.triggered_by_user_id, target.triggered_by_api_key_id, target.input, target.output, target.error_code, target.error_message, target.iterations, target.input_tokens, target.output_tokens, target.metadata, target.cancel_requested_at, target.queued_at, target.started_at, target.finished_at, target.created_at, target.webhook_url
)
SELECT id, agent_id, session_id, mode, status, source, triggered_by_user_id, triggered_by_api_key_id, input, output, error_code, error_message, iterations, input_tokens, output_tokens, metadata, cancel_requested_at, queued_at, started_at, finished_at, created_at, webhook_url FROM updated
UNION ALL
SELECT runs.id, runs.agent_id, runs.session_id, runs.mode, runs.status, runs.source, runs.triggered_by_user_id, runs.triggered_by_api_key_id, runs.input, runs.output, runs.error_code, runs.error_message, runs.iterations, runs.input_tokens, runs.output_tokens, runs.metadata, runs.cancel_requested_at, runs.queued_at, runs.started_at, runs.finished_at, runs.created_at, runs.webhook_url FROM runs WHERE runs.id=$1 AND NOT EXISTS (SELECT 1 FROM updated)
LIMIT 1
`

type RequestRunCancelParams struct {
	ID                pgtype.UUID        `json:"id"`
	CancelRequestedAt pgtype.Timestamptz `json:"cancel_requested_at"`
}

type RequestRunCancelRow struct {
	ID                  pgtype.UUID        `json:"id"`
	AgentID             pgtype.UUID        `json:"agent_id"`
	SessionID           pgtype.UUID        `json:"session_id"`
	Mode                string             `json:"mode"`
	Status              string             `json:"status"`
	Source              string             `json:"source"`
	TriggeredByUserID   pgtype.UUID        `json:"triggered_by_user_id"`
	TriggeredByApiKeyID pgtype.UUID        `json:"triggered_by_api_key_id"`
	Input               []byte             `json:"input"`
	Output              pgtype.Text        `json:"output"`
	ErrorCode           pgtype.Text        `json:"error_code"`
	ErrorMessage        pgtype.Text        `json:"error_message"`
	Iterations          int32              `json:"iterations"`
	InputTokens         pgtype.Int8        `json:"input_tokens"`
	OutputTokens        pgtype.Int8        `json:"output_tokens"`
	Metadata            []byte             `json:"metadata"`
	CancelRequestedAt   pgtype.Timestamptz `json:"cancel_requested_at"`
	QueuedAt            pgtype.Timestamptz `json:"queued_at"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	FinishedAt          pgtype.Timestamptz `json:"finished_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	WebhookUrl          pgtype.Text        `json:"webhook_url"`
}

func (q *Queries) RequestRunCancel(ctx context.Context, arg RequestRunCancelParams) (RequestRunCancelRow, error) {
	row := q.db.QueryRow(ctx, requestRunCancel, arg.ID, arg.CancelRequestedAt)
	var i RequestRunCancelRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.SessionID,
		&i.Mode,
		&i.Status,
		&i.Source,
		&i.TriggeredByUserID,
		&i.TriggeredByApiKeyID,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Iterations,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Metadata,
		&i.CancelRequestedAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.WebhookUrl,
	)
	return i, err
}

const runCancelRequested = `-- name: RunCancelRequested :one
SELECT (cancel_requested_at IS NOT NULL)::boolean AS requested FROM runs WHERE id=$1
`

func (q *Queries) RunCancelRequested(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, runCancelRequested, id)
	var requested bool
	err := row.Scan(&requested)
	return requested, err
}

const sessionHasActiveRuns = `-- name: SessionHasActiveRuns :one
SELECT EXISTS(SELECT 1 FROM runs WHERE session_id=$1 AND status IN ('queued','running'))
`

func (q *Queries) SessionHasActiveRuns(ctx context.Context, sessionID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, sessionHasActiveRuns, sessionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const startQueuedRun = `-- name: StartQueuedRun :one
UPDATE runs SET status='running',started_at=$2
WHERE id=$1 AND status='queued'
RETURNING id, agent_id, session_id, mode, status, source, triggered_by_user_id, triggered_by_api_key_id, input, output, error_code, error_message, iterations, input_tokens, output_tokens, metadata, cancel_requested_at, queued_at, started_at, finished_at, created_at, webhook_url
`

type StartQueuedRunParams struct {
	ID        pgtype.UUID        `json:"id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) StartQueuedRun(ctx context.Context, arg StartQueuedRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, startQueuedRun, arg.ID, arg.StartedAt)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.SessionID,
		&i.Mode,
		&i.Status,
		&i.Source,
		&i.TriggeredByUserID,
		&i.TriggeredByApiKeyID,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Iterations,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Metadata,
		&i.CancelRequestedAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.WebhookUrl,
	)
	return i, err
}

const updatePromptTokenCalibration = `-- name: UpdatePromptTokenCalibration :execrows
UPDATE sessions
SET last_prompt_estimated_tokens=$1,
    last_prompt_tokens=$2,
    updated_at=GREATEST(updated_at,$3)
WHERE id=$4 AND deleted_at IS NULL
`

type UpdatePromptTokenCalibrationParams struct {
	EstimatedTokens pgtype.Int8        `json:"estimated_tokens"`
	ActualTokens    pgtype.Int8        `json:"actual_tokens"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SessionID       pgtype.UUID        `json:"session_id"`
}

func (q *Queries) UpdatePromptTokenCalibration(ctx context.Context, arg UpdatePromptTokenCalibrationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePromptTokenCalibration,
		arg.EstimatedTokens,
		arg.ActualTokens,
		arg.UpdatedAt,
		arg.SessionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
