// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAgentSkill = `-- name: AddAgentSkill :exec
INSERT INTO agent_skills (agent_id,skill_id) VALUES ($1,$2)
`

type AddAgentSkillParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	SkillID pgtype.UUID `json:"skill_id"`
}

func (q *Queries) AddAgentSkill(ctx context.Context, arg AddAgentSkillParams) error {
	_, err := q.db.Exec(ctx, addAgentSkill, arg.AgentID, arg.SkillID)
	return err
}

const createSkill = `-- name: CreateSkill :exec
INSERT INTO skills (id,name,description,source_type,source_filename,content,checksum,tool_refs,created_by,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
`

type CreateSkillParams struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	SourceType     string             `json:"source_type"`
	SourceFilename string             `json:"source_filename"`
	Content        string             `json:"content"`
	Checksum       string             `json:"checksum"`
	ToolRefs       []string           `json:"tool_refs"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) error {
	_, err := q.db.Exec(ctx, createSkill,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SourceType,
		arg.SourceFilename,
		arg.Content,
		arg.Checksum,
		arg.ToolRefs,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAgentSkills = `-- name: DeleteAgentSkills :exec
DELETE FROM agent_skills WHERE agent_id=$1
`

func (q *Queries) DeleteAgentSkills(ctx context.Context, agentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentSkills, agentID)
	return err
}

const deleteSkill = `-- name: DeleteSkill :execrows
DELETE FROM skills WHERE id=$1
`

func (q *Queries) DeleteSkill(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSkill, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSkill = `-- name: GetSkill :one
SELECT id, name, description, source_type, source_filename, content, checksum, created_by, created_at, updated_at, tool_refs FROM skills WHERE id=$1
`

func (q *Queries) GetSkill(ctx context.Context, id pgtype.UUID) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkill, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.SourceFilename,
		&i.Content,
		&i.Checksum,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ToolRefs,
	)
	return i, err
}

const listAgentSkillIDs = `-- name: ListAgentSkillIDs :many
SELECT b.skill_id FROM agent_skills b JOIN skills s ON s.id=b.skill_id
WHERE b.agent_id=$1 ORDER BY lower(s.name),s.id
`

func (q *Queries) ListAgentSkillIDs(ctx context.Context, agentID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAgentSkillIDs, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var skill_id pgtype.UUID
		if err := rows.Scan(&skill_id); err != nil {
			return nil, err
		}
		items = append(items, skill_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkills = `-- name: ListSkills :many
SELECT id,name,description,source_type,source_filename,checksum,tool_refs,created_by,created_at,updated_at FROM skills
WHERE ($2::timestamptz IS NULL OR (created_at,id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC,id DESC LIMIT $1
`

type ListSkillsParams struct {
	Limit      int32              `json:"limit"`
	BeforeTime pgtype.Timestamptz `json:"before_time"`
	BeforeID   pgtype.UUID        `json:"before_id"`
}

type ListSkillsRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	SourceType     string             `json:"source_type"`
	SourceFilename string             `json:"source_filename"`
	Checksum       string             `json:"checksum"`
	ToolRefs       []string           `json:"tool_refs"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSkills(ctx context.Context, arg ListSkillsParams) ([]ListSkillsRow, error) {
	rows, err := q.db.Query(ctx, listSkills, arg.Limit, arg.BeforeTime, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSkillsRow{}
	for rows.Next() {
		var i ListSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SourceType,
			&i.SourceFilename,
			&i.Checksum,
			&i.ToolRefs,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSkills = `-- name: LockSkills :exec
SELECT pg_advisory_xact_lock(724391823)
`

func (q *Queries) LockSkills(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockSkills)
	return err
}

const resolveAgentSkills = `-- name: ResolveAgentSkills :many
SELECT s.id, s.name, s.description, s.source_type, s.source_filename, s.content, s.checksum, s.created_by, s.created_at, s.updated_at, s.tool_refs FROM skills s JOIN agent_skills b ON b.skill_id=s.id
WHERE b.agent_id=$1 ORDER BY lower(s.name),s.id
`

func (q *Queries) ResolveAgentSkills(ctx context.Context, agentID pgtype.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, resolveAgentSkills, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SourceType,
			&i.SourceFilename,
			&i.Content,
			&i.Checksum,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ToolRefs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
