// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tools.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAgentMCPServer = `-- name: AddAgentMCPServer :exec
INSERT INTO agent_mcp_servers (agent_id,mcp_server_id) VALUES ($1,$2)
`

type AddAgentMCPServerParams struct {
	AgentID     pgtype.UUID `json:"agent_id"`
	McpServerID pgtype.UUID `json:"mcp_server_id"`
}

func (q *Queries) AddAgentMCPServer(ctx context.Context, arg AddAgentMCPServerParams) error {
	_, err := q.db.Exec(ctx, addAgentMCPServer, arg.AgentID, arg.McpServerID)
	return err
}

const addAgentTool = `-- name: AddAgentTool :exec
INSERT INTO agent_tools (agent_id,tool_id) VALUES ($1,$2)
`

type AddAgentToolParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	ToolID  pgtype.UUID `json:"tool_id"`
}

func (q *Queries) AddAgentTool(ctx context.Context, arg AddAgentToolParams) error {
	_, err := q.db.Exec(ctx, addAgentTool, arg.AgentID, arg.ToolID)
	return err
}

const createMCPServer = `-- name: CreateMCPServer :exec
INSERT INTO mcp_servers (id,slug,display_name,url,secret_headers_ciphertext,secret_header_names,allowed_tools,tools_cache,status,last_error,last_synced_at,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
`

type CreateMCPServerParams struct {
	ID                      pgtype.UUID        `json:"id"`
	Slug                    string             `json:"slug"`
	DisplayName             string             `json:"display_name"`
	Url                     string             `json:"url"`
	SecretHeadersCiphertext []byte             `json:"secret_headers_ciphertext"`
	SecretHeaderNames       []string           `json:"secret_header_names"`
	AllowedTools            []string           `json:"allowed_tools"`
	ToolsCache              []byte             `json:"tools_cache"`
	Status                  string             `json:"status"`
	LastError               []byte             `json:"last_error"`
	LastSyncedAt            pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateMCPServer(ctx context.Context, arg CreateMCPServerParams) error {
	_, err := q.db.Exec(ctx, createMCPServer,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.Url,
		arg.SecretHeadersCiphertext,
		arg.SecretHeaderNames,
		arg.AllowedTools,
		arg.ToolsCache,
		arg.Status,
		arg.LastError,
		arg.LastSyncedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createTool = `-- name: CreateTool :exec
INSERT INTO tools (id,connection_id,slug,display_name,step_label,description,method,url_template,params,public_headers,secret_headers_ciphertext,secret_header_names,timeout_seconds,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
`

type CreateToolParams struct {
	ID                      pgtype.UUID        `json:"id"`
	ConnectionID            pgtype.UUID        `json:"connection_id"`
	Slug                    string             `json:"slug"`
	DisplayName             string             `json:"display_name"`
	StepLabel               string             `json:"step_label"`
	Description             string             `json:"description"`
	Method                  string             `json:"method"`
	UrlTemplate             string             `json:"url_template"`
	Params                  []byte             `json:"params"`
	PublicHeaders           []byte             `json:"public_headers"`
	SecretHeadersCiphertext []byte             `json:"secret_headers_ciphertext"`
	SecretHeaderNames       []string           `json:"secret_header_names"`
	TimeoutSeconds          int32              `json:"timeout_seconds"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTool(ctx context.Context, arg CreateToolParams) error {
	_, err := q.db.Exec(ctx, createTool,
		arg.ID,
		arg.ConnectionID,
		arg.Slug,
		arg.DisplayName,
		arg.StepLabel,
		arg.Description,
		arg.Method,
		arg.UrlTemplate,
		arg.Params,
		arg.PublicHeaders,
		arg.SecretHeadersCiphertext,
		arg.SecretHeaderNames,
		arg.TimeoutSeconds,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAgentMCPServers = `-- name: DeleteAgentMCPServers :exec
DELETE FROM agent_mcp_servers WHERE agent_id=$1
`

func (q *Queries) DeleteAgentMCPServers(ctx context.Context, agentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentMCPServers, agentID)
	return err
}

const deleteAgentTools = `-- name: DeleteAgentTools :exec
DELETE FROM agent_tools WHERE agent_id=$1
`

func (q *Queries) DeleteAgentTools(ctx context.Context, agentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentTools, agentID)
	return err
}

const deleteMCPServer = `-- name: DeleteMCPServer :execrows
DELETE FROM mcp_servers WHERE id=$1
`

func (q *Queries) DeleteMCPServer(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMCPServer, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTool = `-- name: DeleteTool :execrows
DELETE FROM tools WHERE id=$1
`

func (q *Queries) DeleteTool(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTool, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMCPServer = `-- name: GetMCPServer :one
SELECT id, slug, display_name, url, secret_headers_ciphertext, secret_header_names, allowed_tools, tools_cache, status, last_error, last_synced_at, created_at, updated_at, revision FROM mcp_servers WHERE id=$1
`

func (q *Queries) GetMCPServer(ctx context.Context, id pgtype.UUID) (McpServer, error) {
	row := q.db.QueryRow(ctx, getMCPServer, id)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Url,
		&i.SecretHeadersCiphertext,
		&i.SecretHeaderNames,
		&i.AllowedTools,
		&i.ToolsCache,
		&i.Status,
		&i.LastError,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}

const getMCPServerForUpdate = `-- name: GetMCPServerForUpdate :one
SELECT id, slug, display_name, url, secret_headers_ciphertext, secret_header_names, allowed_tools, tools_cache, status, last_error, last_synced_at, created_at, updated_at, revision FROM mcp_servers WHERE id=$1 FOR UPDATE
`

func (q *Queries) GetMCPServerForUpdate(ctx context.Context, id pgtype.UUID) (McpServer, error) {
	row := q.db.QueryRow(ctx, getMCPServerForUpdate, id)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Url,
		&i.SecretHeadersCiphertext,
		&i.SecretHeaderNames,
		&i.AllowedTools,
		&i.ToolsCache,
		&i.Status,
		&i.LastError,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}

const getTool = `-- name: GetTool :one
SELECT id, slug, display_name, description, kind, method, url_template, params, public_headers, secret_headers_ciphertext, secret_header_names, timeout_seconds, created_at, updated_at, connection_id, step_label FROM tools WHERE id=$1
`

func (q *Queries) GetTool(ctx context.Context, id pgtype.UUID) (Tool, error) {
	row := q.db.QueryRow(ctx, getTool, id)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.Kind,
		&i.Method,
		&i.UrlTemplate,
		&i.Params,
		&i.PublicHeaders,
		&i.SecretHeadersCiphertext,
		&i.SecretHeaderNames,
		&i.TimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConnectionID,
		&i.StepLabel,
	)
	return i, err
}

const getToolForUpdate = `-- name: GetToolForUpdate :one
SELECT id, slug, display_name, description, kind, method, url_template, params, public_headers, secret_headers_ciphertext, secret_header_names, timeout_seconds, created_at, updated_at, connection_id, step_label FROM tools WHERE id=$1 FOR UPDATE
`

func (q *Queries) GetToolForUpdate(ctx context.Context, id pgtype.UUID) (Tool, error) {
	row := q.db.QueryRow(ctx, getToolForUpdate, id)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.Kind,
		&i.Method,
		&i.UrlTemplate,
		&i.Params,
		&i.PublicHeaders,
		&i.SecretHeadersCiphertext,
		&i.SecretHeaderNames,
		&i.TimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConnectionID,
		&i.StepLabel,
	)
	return i, err
}

const listAgentMCPServerIDs = `-- name: ListAgentMCPServerIDs :many
SELECT mcp_server_id FROM agent_mcp_servers WHERE agent_id=$1 ORDER BY mcp_server_id
`

func (q *Queries) ListAgentMCPServerIDs(ctx context.Context, agentID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAgentMCPServerIDs, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var mcp_server_id pgtype.UUID
		if err := rows.Scan(&mcp_server_id); err != nil {
			return nil, err
		}
		items = append(items, mcp_server_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentToolIDs = `-- name: ListAgentToolIDs :many
SELECT tool_id FROM agent_tools WHERE agent_id=$1 ORDER BY tool_id
`

func (q *Queries) ListAgentToolIDs(ctx context.Context, agentID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAgentToolIDs, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var tool_id pgtype.UUID
		if err := rows.Scan(&tool_id); err != nil {
			return nil, err
		}
		items = append(items, tool_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTools = `-- name: ListAllTools :many
SELECT id, slug, display_name, description, kind, method, url_template, params, public_headers, secret_headers_ciphertext, secret_header_names, timeout_seconds, created_at, updated_at, connection_id, step_label FROM tools ORDER BY slug
`

func (q *Queries) ListAllTools(ctx context.Context) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listAllTools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tool{}
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.Kind,
			&i.Method,
			&i.UrlTemplate,
			&i.Params,
			&i.PublicHeaders,
			&i.SecretHeadersCiphertext,
			&i.SecretHeaderNames,
			&i.TimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConnectionID,
			&i.StepLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPServers = `-- name: ListMCPServers :many
SELECT id, slug, display_name, url, secret_headers_ciphertext, secret_header_names, allowed_tools, tools_cache, status, last_error, last_synced_at, created_at, updated_at, revision FROM mcp_servers WHERE ($2::timestamptz IS NULL OR (created_at,id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC,id DESC LIMIT $1
`

type ListMCPServersParams struct {
	Limit      int32              `json:"limit"`
	BeforeTime pgtype.Timestamptz `json:"before_time"`
	BeforeID   pgtype.UUID        `json:"before_id"`
}

func (q *Queries) ListMCPServers(ctx context.Context, arg ListMCPServersParams) ([]McpServer, error) {
	rows, err := q.db.Query(ctx, listMCPServers, arg.Limit, arg.BeforeTime, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpServer{}
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Url,
			&i.SecretHeadersCiphertext,
			&i.SecretHeaderNames,
			&i.AllowedTools,
			&i.ToolsCache,
			&i.Status,
			&i.LastError,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTools = `-- name: ListTools :many
SELECT id, slug, display_name, description, kind, method, url_template, params, public_headers, secret_headers_ciphertext, secret_header_names, timeout_seconds, created_at, updated_at, connection_id, step_label FROM tools WHERE ($2::timestamptz IS NULL OR (created_at,id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC,id DESC LIMIT $1
`

type ListToolsParams struct {
	Limit      int32              `json:"limit"`
	BeforeTime pgtype.Timestamptz `json:"before_time"`
	BeforeID   pgtype.UUID        `json:"before_id"`
}

func (q *Queries) ListTools(ctx context.Context, arg ListToolsParams) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listTools, arg.Limit, arg.BeforeTime, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tool{}
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.Kind,
			&i.Method,
			&i.UrlTemplate,
			&i.Params,
			&i.PublicHeaders,
			&i.SecretHeadersCiphertext,
			&i.SecretHeaderNames,
			&i.TimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConnectionID,
			&i.StepLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTooling = `-- name: LockTooling :exec
SELECT pg_advisory_xact_lock(724391822)
`

func (q *Queries) LockTooling(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockTooling)
	return err
}

const recordMCPServerSync = `-- name: RecordMCPServerSync :execrows
UPDATE mcp_servers SET tools_cache=$3,status=$4,last_error=$5,last_synced_at=$6,updated_at=$6
WHERE id=$1 AND revision=$2
`

type RecordMCPServerSyncParams struct {
	ID           pgtype.UUID        `json:"id"`
	Revision     int64              `json:"revision"`
	ToolsCache   []byte             `json:"tools_cache"`
	Status       string             `json:"status"`
	LastError    []byte             `json:"last_error"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) RecordMCPServerSync(ctx context.Context, arg RecordMCPServerSyncParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordMCPServerSync,
		arg.ID,
		arg.Revision,
		arg.ToolsCache,
		arg.Status,
		arg.LastError,
		arg.LastSyncedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveAgentHTTPTools = `-- name: ResolveAgentHTTPTools :many
SELECT
    t.id, t.slug, t.display_name, t.description, t.kind, t.method, t.url_template, t.params, t.public_headers, t.secret_headers_ciphertext, t.secret_header_names, t.timeout_seconds, t.created_at, t.updated_at, t.connection_id, t.step_label,
    c.id AS api_connection_id,
    c.slug AS api_connection_slug,
    c.display_name AS api_connection_display_name,
    c.base_url AS api_connection_base_url,
    c.public_headers AS api_connection_public_headers,
    c.secret_headers_ciphertext AS api_connection_secret_headers_ciphertext,
    c.secret_header_names AS api_connection_secret_header_names,
    c.created_at AS api_connection_created_at,
    c.updated_at AS api_connection_updated_at
FROM tools t
JOIN agent_tools b ON b.tool_id=t.id
LEFT JOIN api_connections c ON c.id=t.connection_id
WHERE b.agent_id=$1
ORDER BY t.slug,t.id
`

type ResolveAgentHTTPToolsRow struct {
	ID                                   pgtype.UUID        `json:"id"`
	Slug                                 string             `json:"slug"`
	DisplayName                          string             `json:"display_name"`
	Description                          string             `json:"description"`
	Kind                                 string             `json:"kind"`
	Method                               string             `json:"method"`
	UrlTemplate                          string             `json:"url_template"`
	Params                               []byte             `json:"params"`
	PublicHeaders                        []byte             `json:"public_headers"`
	SecretHeadersCiphertext              []byte             `json:"secret_headers_ciphertext"`
	SecretHeaderNames                    []string           `json:"secret_header_names"`
	TimeoutSeconds                       int32              `json:"timeout_seconds"`
	CreatedAt                            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                            pgtype.Timestamptz `json:"updated_at"`
	ConnectionID                         pgtype.UUID        `json:"connection_id"`
	StepLabel                            string             `json:"step_label"`
	ApiConnectionID                      pgtype.UUID        `json:"api_connection_id"`
	ApiConnectionSlug                    pgtype.Text        `json:"api_connection_slug"`
	ApiConnectionDisplayName             pgtype.Text        `json:"api_connection_display_name"`
	ApiConnectionBaseUrl                 pgtype.Text        `json:"api_connection_base_url"`
	ApiConnectionPublicHeaders           []byte             `json:"api_connection_public_headers"`
	ApiConnectionSecretHeadersCiphertext []byte             `json:"api_connection_secret_headers_ciphertext"`
	ApiConnectionSecretHeaderNames       []string           `json:"api_connection_secret_header_names"`
	ApiConnectionCreatedAt               pgtype.Timestamptz `json:"api_connection_created_at"`
	ApiConnectionUpdatedAt               pgtype.Timestamptz `json:"api_connection_updated_at"`
}

func (q *Queries) ResolveAgentHTTPTools(ctx context.Context, agentID pgtype.UUID) ([]ResolveAgentHTTPToolsRow, error) {
	rows, err := q.db.Query(ctx, resolveAgentHTTPTools, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveAgentHTTPToolsRow{}
	for rows.Next() {
		var i ResolveAgentHTTPToolsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.Kind,
			&i.Method,
			&i.UrlTemplate,
			&i.Params,
			&i.PublicHeaders,
			&i.SecretHeadersCiphertext,
			&i.SecretHeaderNames,
			&i.TimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConnectionID,
			&i.StepLabel,
			&i.ApiConnectionID,
			&i.ApiConnectionSlug,
			&i.ApiConnectionDisplayName,
			&i.ApiConnectionBaseUrl,
			&i.ApiConnectionPublicHeaders,
			&i.ApiConnectionSecretHeadersCiphertext,
			&i.ApiConnectionSecretHeaderNames,
			&i.ApiConnectionCreatedAt,
			&i.ApiConnectionUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAgentMCPServers = `-- name: ResolveAgentMCPServers :many
SELECT s.id, s.slug, s.display_name, s.url, s.secret_headers_ciphertext, s.secret_header_names, s.allowed_tools, s.tools_cache, s.status, s.last_error, s.last_synced_at, s.created_at, s.updated_at, s.revision FROM mcp_servers s JOIN agent_mcp_servers b ON b.mcp_server_id=s.id WHERE b.agent_id=$1 ORDER BY s.slug,s.id
`

func (q *Queries) ResolveAgentMCPServers(ctx context.Context, agentID pgtype.UUID) ([]McpServer, error) {
	rows, err := q.db.Query(ctx, resolveAgentMCPServers, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpServer{}
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Url,
			&i.SecretHeadersCiphertext,
			&i.SecretHeaderNames,
			&i.AllowedTools,
			&i.ToolsCache,
			&i.Status,
			&i.LastError,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMCPServer = `-- name: UpdateMCPServer :one
UPDATE mcp_servers SET slug=$2,display_name=$3,url=$4,secret_headers_ciphertext=$5,secret_header_names=$6,allowed_tools=$7,tools_cache=$8,status=$9,last_error=$10,last_synced_at=$11,updated_at=$12,revision=revision+1
WHERE id=$1 RETURNING id, slug, display_name, url, secret_headers_ciphertext, secret_header_names, allowed_tools, tools_cache, status, last_error, last_synced_at, created_at, updated_at, revision
`

type UpdateMCPServerParams struct {
	ID                      pgtype.UUID        `json:"id"`
	Slug                    string             `json:"slug"`
	DisplayName             string             `json:"display_name"`
	Url                     string             `json:"url"`
	SecretHeadersCiphertext []byte             `json:"secret_headers_ciphertext"`
	SecretHeaderNames       []string           `json:"secret_header_names"`
	AllowedTools            []string           `json:"allowed_tools"`
	ToolsCache              []byte             `json:"tools_cache"`
	Status                  string             `json:"status"`
	LastError               []byte             `json:"last_error"`
	LastSyncedAt            pgtype.Timestamptz `json:"last_synced_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateMCPServer(ctx context.Context, arg UpdateMCPServerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, updateMCPServer,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.Url,
		arg.SecretHeadersCiphertext,
		arg.SecretHeaderNames,
		arg.AllowedTools,
		arg.ToolsCache,
		arg.Status,
		arg.LastError,
		arg.LastSyncedAt,
		arg.UpdatedAt,
	)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Url,
		&i.SecretHeadersCiphertext,
		&i.SecretHeaderNames,
		&i.AllowedTools,
		&i.ToolsCache,
		&i.Status,
		&i.LastError,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}

const updateTool = `-- name: UpdateTool :execrows
UPDATE tools SET connection_id=$2,slug=$3,display_name=$4,step_label=$5,description=$6,method=$7,url_template=$8,params=$9,public_headers=$10,secret_headers_ciphertext=$11,secret_header_names=$12,timeout_seconds=$13,updated_at=$14
WHERE id=$1
`

type UpdateToolParams struct {
	ID                      pgtype.UUID        `json:"id"`
	ConnectionID            pgtype.UUID        `json:"connection_id"`
	Slug                    string             `json:"slug"`
	DisplayName             string             `json:"display_name"`
	StepLabel               string             `json:"step_label"`
	Description             string             `json:"description"`
	Method                  string             `json:"method"`
	UrlTemplate             string             `json:"url_template"`
	Params                  []byte             `json:"params"`
	PublicHeaders           []byte             `json:"public_headers"`
	SecretHeadersCiphertext []byte             `json:"secret_headers_ciphertext"`
	SecretHeaderNames       []string           `json:"secret_header_names"`
	TimeoutSeconds          int32              `json:"timeout_seconds"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateTool(ctx context.Context, arg UpdateToolParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTool,
		arg.ID,
		arg.ConnectionID,
		arg.Slug,
		arg.DisplayName,
		arg.StepLabel,
		arg.Description,
		arg.Method,
		arg.UrlTemplate,
		arg.Params,
		arg.PublicHeaders,
		arg.SecretHeadersCiphertext,
		arg.SecretHeaderNames,
		arg.TimeoutSeconds,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
